Feat/profile/edit profile screen UI and tests
PeriodPals/periodpals pull request #108
Opened 2024-10-31 15:37 UTC by Harrish92

# Title
## Description
This PR introduces the UI for `EditProfileScreen`, adds the option to change the profile image, and implements validation logic for the fields. It also includes tests for these functionalities. It closes issue #88.

## Changes
- Created the UI for `EditProfileScreen`.
- Added the option to change the profile image when the `add_circle_icon` is clicked.
- Implemented validation logic to check if the name, date of birth, and description fields are filled.
- Added tests to verify the UI element.

## Files 
#### Added
- `app/src/androidTest/java/com/android/periodpals/ui/profile/EditProfileScreenTest.kt`

#### Modified
- `app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt`

#### Removed
- None

## Dependencies Added
- None

## Testing
- Verified that the UI elements on the `EditProfileScreen` are correctly displayed.
- Ensured that all tests for the `EditProfileScreen` pass successfully.

## Screenshots (if applicable)
- #89

2024-11-01 13:45 UTC, francelu requested changes
## Summary
Good initial implementation of the `EditProfileScreen`. Improvements are needed for consistency and better alignment with the Figma design.

## Important
#### Code Quality
- Enhance code consistency as noted in the comments.

#### Functionality
- Ensure the UI matches the Figma specifications more closely. Check other screens' code for consistency and inspiration.

## Testing
- Review the existing tests to confirm they cover the updated UI and logic. Check other screens' tests for consistency, completeness, and inspiration.

## Suggestions
- Address the changes highlighted in the code and file comments.

## Steps before PR approved
- Implement the changes detailed in the code and file comments to ensure consistency and Figma alignment.

2024-11-01 13:45 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
> +          ProfileText("Mandatory Fields")
It's good to put the component in a separate function. However, this could be put in `ui/components` under `ProfileComponents.kt` as it could be used in `Profile` too, maybe even `CreateProfileScreen`.

2024-11-01 13:45 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
> +          Row(horizontalArrangement = Arrangement.Start, modifier = Modifier.testTag("email_row")) {
To be determined with PO and team if we want the email to be modifiable. Contact PO.

2024-11-01 13:45 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
> +          ProfileField(
It's a good idea as before to put this in a separate function. However, this doesn't match the Figma at all. Remember the bootcamp, this was just a simple `OutlinedTextField` were the value in it will be fetched from the profile VM.  
Change this and the above one for the whole screen components.

2024-11-01 13:45 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
> +                  Toast.makeText(context, "Profile saved", Toast.LENGTH_SHORT).show()
This should navigate back to `Screen.PROFILE`.

2024-11-01 13:45 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
> +}
Please relocate and change this code as mentioned above.

2024-11-01 13:45 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
> +      },
The `BottomNavigationBar` must **ABSOLUTELY NOT** be displayed on this screen. Please check the Figma !!

2024-11-02 15:29 UTC, charliemangano commented
Hi @Harrish92! I just merged a PR (#102) that refactors every testTag in a separate file for better maintainability. Can you take a look at how it's done and apply it to your code?

2024-11-03 17:39 UTC, Harrish92 commented on app/src/main/res/values-night/themes.xml
Optimization import was used on this file

2024-11-03 17:40 UTC, Harrish92 commented on app/src/main/res/values/themes.xml
Optimization import was used on this file

2024-11-03 19:28 UTC, Harrish92 commented on app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
> +          Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.Center) {
If we defined the vertical parameter of column as center, then it would supersede the alignments for the texts. So, it'd be better to keep it that way.

2024-11-04 19:27 UTC, francelu commented on app/src/main/res/values-night/themes.xml
I don't see why optimizing imports would make this change.

2024-11-04 20:00 UTC, francelu commented on app/src/androidTest/java/com/android/periodpals/ui/profile/EditProfileTest.kt
> +    composeTestRule.onNodeWithTag(EditProfileScreen.EDIT_PROFILE_SCREEN).assertIsDisplayed()
Should be the first line.

2024-11-04 20:02 UTC, francelu commented on app/src/main/java/com/android/periodpals/resources/C.kt
>      }
Missing test tags for the profile "sections" / texts.

2024-11-04 20:05 UTC, francelu commented on app/src/androidTest/java/com/android/periodpals/ui/profile/EditProfileTest.kt
>    }
- Rename: `allComponentsAreDisplayed`.
- Missing check for profile section for mandatory.
- Reorder the checks in the order they are displayed.

2024-11-04 20:05 UTC, francelu commented on app/src/androidTest/java/com/android/periodpals/ui/profile/EditProfileTest.kt
> +  fun createValidProfile() {
Rename: `saveValidProfile`. Same for the following tests `saveInvalid...`.

2024-11-04 20:10 UTC, francelu commented on app/src/androidTest/java/com/android/periodpals/ui/profile/EditProfileTest.kt
> +  }
This should be the first `saveInvalid...()` test.  

Also, in each test, the order of the tags should be email, name, dob, description as it is on the screen, rather than name, dob, description, email.

2024-11-04 20:28 UTC, Harrish92 commented on app/src/main/res/values-night/themes.xml
It's because I set up optimizing imports on all the files

2024-11-05 10:16 UTC, Harrish92 commented on app/src/main/res/values-night/themes.xml
I reverted all the changes.

2024-11-05 11:07 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
> +          Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.Center) {
Yeah you can just text align start or left, whichever it is. Just for code consistency with other screen too.

2024-11-05 11:31 UTC, francelu commented
Hey, I've just noticed you answered to one of my in-line comments. Please check my proposition [here](https://github.com/PeriodPals/periodpals/pull/108#discussion_r1829163997). :)

2024-11-05 17:42 UTC, Harrish92 commented on app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
> +          Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.Center) {
Putting the column as center would supersede the alignments for the texts, which means that it would be on the center regardless of `textAlign`. Following the second option would break the implementation of the icon on the image.

2024-11-05 18:10 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
> +          Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.Center) {
Okay, then keep it like that for now. Minor issue. :)

2024-11-05 20:45 UTC, francelu requested changes
A few nitpicks to correct before PR approved for merge.  We're almost there !! :)))

2024-11-05 20:45 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
> +                  Icons.Filled.PhotoCamera,
Please use `Icons.Outlined.Edit` as most of the time we used Outlined icons in our app. This would also fit better to the Figma design.

2024-11-05 20:45 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
> +
Please remove this empty line, I've already mentioned that change before. Thanks ! Keep up the good work :)

2024-11-05 20:45 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
> +      // TODO: Check existing email from Supabase
Delete this `TODO`. When we will implement the VM, we will take care of that naturally :)

2024-11-05 20:45 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
> +                val emailErrorMessage = validateEmail(email)
- Instead of having `emailErrorMessage` here, use the `validateEmail` directly in the `validateFields` where currently we have `email.isEmpty()`.
- Please also reorder the `validateFields` to check the validity of the fields in the following order: email, name, dob, description (as they are displayed on the screen). This makes the understanding of the code better as their order is consistent across the code.

2024-11-05 20:45 UTC, francelu commented on app/src/main/java/com/android/periodpals/resources/C.kt
> +      const val NAME_FIELD = "nameField"
For consistency with the UI, please exchange these two values; i.e. ... then `EMAIL_FIELD` then `NAME_FIELD` then `DOB_FIELD` then ...

2024-11-05 20:45 UTC, francelu commented on app/src/androidTest/java/com/android/periodpals/ui/profile/EditProfileTest.kt
> +    composeTestRule.onNodeWithTag(TopAppBar.GO_BACK_BUTTON).assertIsDisplayed()
You're missing the top app bar title verification: is displayed and text equals ...

2024-11-05 20:45 UTC, francelu commented on app/src/androidTest/java/com/android/periodpals/ui/profile/EditProfileTest.kt
> +    composeTestRule.onNodeWithTag(EditProfileScreen.SCREEN).assertIsDisplayed()
Please reorder these tags as they are in the `resources/C.kt` file.

2024-11-05 20:45 UTC, francelu commented on app/src/main/java/com/android/periodpals/resources/C.kt
> +      const val MANDATORY_FIELDS = "mandatoryFields"
Typo: `MANDATORY_FIELD = "mandatoryField"` or eventually mandatory section.

2024-11-06 08:47 UTC, francelu approved these changes
# PR Review

## Summary  
Overall, a strong effort. The code mostly adheres to the standards and the Figma design, and the intended functionality is clear.

## Important

### Code Quality  
The code is generally readable and consistent. However, there are a few areas where the naming conventions and spacing can be improved to better align with project guidelines.

### Functionality  
The feature works as expected, handling most scenarios effectively.

## Testing  
UI tests appear thorough and well-implemented.

## Documentation  
No changes are needed to external documentation.

## Suggestions  
Consider implementing the suggested naming convention changes for better readability and consistency.

## Steps before PR Merge
**Address the code naming changes as mentioned in the comments.**

2024-11-06 08:47 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
> +    }
Code cleanness : `else -> ""`

2024-11-06 08:47 UTC, francelu commented on app/src/androidTest/java/com/android/periodpals/ui/profile/EditProfileTest.kt
> +  fun saveInvalidProfileNoName() {
Naming convention : `editInvalid...`.

2024-11-06 08:47 UTC, francelu commented on app/src/androidTest/java/com/android/periodpals/ui/profile/EditProfileTest.kt
> +  fun saveInvalidProfileNoDOB() {
Same here, naming convention : `editInvalid...`.

2024-11-06 08:47 UTC, francelu commented on app/src/androidTest/java/com/android/periodpals/ui/profile/EditProfileTest.kt
> +  fun saveInvalidProfileNoDescription() {
Same here, naming convention : `editInvalid...`.

2024-11-06 08:47 UTC, francelu commented on app/src/androidTest/java/com/android/periodpals/ui/profile/EditProfileTest.kt
> +  fun saveInvalidProfileNoEmail() {
Same here, naming convention : `editInvalid...`.

2024-11-06 08:47 UTC, francelu commented on app/src/androidTest/java/com/android/periodpals/ui/profile/EditProfileTest.kt
> +  fun saveInvalidProfileAllEmptyFields() {
Same here, naming convention : `editInvalid...`.

2024-11-07 11:04 UTC, taghizadlaura requested changes
## Summary
They are only small adjustments to fit the figma (please see comments).
## Important 
#### Code Quality
LGTM
#### Functionality
LGTM
## Testing
LGTM please check when you change the code that it doesn't affect the tests.
## Documentation
LGTM. There's a lot of comments which strongly contribute to the understanding of the code.
## Steps before PR approved
Please read the comments to fit more to the figma

2024-11-07 14:13 UTC, taghizadlaura requested changes
Please also remove the color of the button.

2024-11-07 14:13 UTC, taghizadlaura commented on app/src/main/java/com/android/periodpals/ui/profile/EditProfile.kt
> +              colors = ButtonDefaults.buttonColors(Color(0xFFD9D9D9)),
Thank you for removing the background of the button, but could you also remove the color you assigned since it doesn't fit the figma.

2024-11-07 16:10 UTC, taghizadlaura approved these changes
LGTM now :)

2024-11-07 16:10 UTC, merged