Fix/geolocation/integrate location service
PeriodPals/periodpals pull request #110
Opened 2024-10-31 18:22 UTC by lazarinibruno

# Integrate Location Service and Remove old code

## Description
This PR integrates the newly written location service.  By doing so, the logic for the location is contained within the `LocationServiceImpl` class. Moreover, the app requests the access to the location at the right time (namely, when clicking on the Map). It closes issues #78 and #95. 

## Changes
- Removes the location access request logic from the main (since it is now handled by `LocationServiceImpl`).
- Instantiates a `locationService` in the main activity, which is then passed as an argument to `PeriodPalsApp` and consecutively to `MapScreen`.
- Adapts the `MapScreen` to the new implementation. 
- Adapted the `MapScreenTest`
 
## Files 

#### Added
None.

#### Modified
- `MainActivity.kt`
- `Map.kt`
- `MapScreenTest.kt`

#### Removed
None.

## Dependencies Added
None.

## Testing
- I adapted the `MapScreenTest` to work with the new location service.
- I did two tests from the test that checks whether the map is shown when permission is granted:
    - One for when approximate location is granted
    - One for when precise location is granted 

## Screenshots
![image](https://github.com/user-attachments/assets/e7005676-feb7-44eb-857f-7552f3fb2035)

Location access request in the right screen (੭*ˊᵕˋ)੭

2024-11-03 10:00 UTC, agonzalez-r requested changes
## Summary
Thank you for this implementation! It contributes a lot on the Map feature of the app. 
Sadly I can't manually check if it works at expected (my emulator is only connected to wifi when I'm on campus for some reason so I can't login). But all the tests pass. 
## Important (which includes)
#### Code Quality
- I left a comment about the parameter `locationPermissionGranted` for `MapViewContainer()`, I think it should be replaced directly by `locationGrantedType` so you can directly use it 
#### Functionality
- ***Question***: where is the distinction between the precise and approximate location granted type treated? Since it's the same code for both types, I figure that it is automatically treated different by the location listener, but I'm not sure
## Testing
The tests for this screen are not complete: 
- Mainly, there is no tests to assert that components like `BottomNavigationMenu` and `TopAppBar` are correctly displayed (which also is not consistent with the rest of screen tests)
- For all tests (which difference is only the type of permission granted) you assert the same thing, only that map view exists. I think each tests should verify something more specific for each type (if possible). At least, when no permission is granted, could you verify that the default location is displayed? 


## Suggestions
- Tests more precise for different typer of granted permission types? (again, not sure if this is possible)
## Steps before PR approved
- Add tests for the correct display of `BottomNavigationMenu` and `TopAppBar` in `MapScreenTest.kt`
- Modify `MapViewContainer()` parameters for better code quality

2024-11-03 21:21 UTC, lazarinibruno commented
> * For all tests (which difference is only the type of permission granted) you assert the same thing, only that map view exists. I think each tests should verify something more specific for each type (if possible). At least, when no permission is granted, could you verify that the default location is displayed?

Well, as @taghizadlaura said in some of the meetings, there is no direct way of testing the content of the map. This is why we only assert that the map is displayed given the different permissions. Moreover, this PR focuses on the integration of the location service, not in the map itself.

2024-11-03 21:38 UTC, lazarinibruno commented on app/src/main/java/com/android/periodpals/ui/map/Map.kt
> +  val locationPermissionGranted =
I know. I did that as a temporary fix to integrate the location service. In S4, I will finish the location service to handle what to do given the different types of location access granted #130.

2024-11-04 10:01 UTC, agonzalez-r approved these changes
Okay, we'll get to the changes later.

2024-11-05 13:29 UTC, taghizadlaura commented on app/src/main/java/com/android/periodpals/ui/map/Map.kt
> +fun MapScreen(locationService: LocationServiceImpl, navigationActions: NavigationActions) {
Problem with the declaration in the MainActivity

2024-11-05 14:49 UTC, lazarinibruno commented on app/src/main/java/com/android/periodpals/MainActivity.kt
> +        MapScreen(Modifier.fillMaxSize(), locationService, navigationActions)
Should be fixed now.

2024-11-05 14:56 UTC, taghizadlaura requested changes

2024-11-05 14:56 UTC, taghizadlaura commented on app/src/androidTest/java/com/android/periodpals/ui/map/MapScreenTest.kt
> +            modifier = Modifier,
Same problem as the previous one in the MainActivity

2024-11-05 14:56 UTC, taghizadlaura commented on app/src/androidTest/java/com/android/periodpals/ui/map/MapScreenTest.kt
> +            modifier = Modifier,
same here

2024-11-05 14:56 UTC, taghizadlaura commented on app/src/androidTest/java/com/android/periodpals/ui/map/MapScreenTest.kt
> +            modifier = Modifier,
same here

2024-11-05 15:27 UTC, taghizadlaura approved these changes
LGTM now, but there is a bug on the approximate location. We decided to fix it in a different task : #130

2024-11-05 16:06 UTC, merged