Fix/style/layout responsiveness/set up
PeriodPals/periodpals pull request #121
Opened 2024-11-01 11:35 UTC by francelu

# Title
Setup Padding Dimensions and Typography for Responsive Design (#82 Subtask)

## Description
This PR sets up standardised padding and typography to ensure responsive design and visual consistency across all screens, aligning with the App Style Guide. It includes utility files for padding and custom fonts for consistent typography, supporting subtask #82 and improving overall readability and user experience.

## Changes
- Added standardized padding dimensions for UI components.
- Configured typography settings to improve readability and maintain consistency with the App Style Guide.
- **DIDN'T CHANGE IN SCREENS YET.** To be done in next subtasks of #82.

## Files 

#### Added
`app/src/main/java/com/android/periodpals/ui/theme/` :
- `Dimens.kt` (for padding values)
- `AppUtil.kt` (for providing app dimensions)
`app/src/main/res/font`:
- `nunito_sans_black.ttf`
- `nunito_sans_black_italic.ttf`
- `nunito_sans_bold.ttf`
- `nunito_sans_bold_italic.ttf`
- `nunito_sans_extra_bold.ttf`
- `nunito_sans_extra_bold_italic.ttf`
- `nunito_sans_extra_light.ttf`
- `nunito_sans_extra_light_italic.ttf`
- `nunito_sans_italic.ttf`
- `nunito_sans_light.ttf`
- `nunito_sans_light_italic.ttf`
- `nunito_sans_regular.ttf`
- `nunito_sans_semi_bold.ttf`
- `nunito_sans_semi_bold_italic.ttf`

#### Modified
- `typography.xml` (for font and size configurations)

## Dependencies Added
None

## Testing
- Direct testing is not applicable as this setup resembles our colour theme configuration.
- Visual inspection needed to verify padding and typography consistency across the app on each screen (to be followed in #82 and subtasks).

2024-11-01 17:23 UTC, Harrish92 requested changes
## Summary
Comments for the `ProvideAppUtils` class are needed to improve code readability and maintainability. Otherwise, good job on standardizing padding and typography. 
## Documentation
- Ensure that the comments are clear and provide sufficient information for future developers to understand the code.

## Steps before PR approved
- Add detailed comments to the `ProvideAppUtils` class to improve code readability and maintainability.

2024-11-01 17:23 UTC, Harrish92 commented on app/src/main/java/com/android/periodpals/ui/theme/AppUtil.kt
Could you please write comments to clarify what exactly ProvideAppUtils does?

2024-11-03 09:39 UTC, Harrish92 approved these changes
LGTM

2024-11-03 09:42 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/theme/AppUtil.kt
Added.

2024-11-03 21:03 UTC, lazarinibruno commented on app/src/main/java/com/android/periodpals/ui/theme/Dimens.kt
> +data class Dimens(
Question: I'm curious, where do all of these values come from?

2024-11-03 21:04 UTC, lazarinibruno commented on app/src/main/java/com/android/periodpals/ui/theme/Theme.kt
> +  Toast.makeText(LocalContext.current, dims, Toast.LENGTH_SHORT).show()
Since it is marked as to be deleted, why is it still there?

2024-11-03 21:11 UTC, lazarinibruno requested changes
## Summary

Thanks for the hard work :DD

- The addition of `Dimens.kt`, `Type.kt` and `Theme.kt` help will help have an app that looks good and is consistent.
  

## Improvements

- Could you add a short documentation above the `Dimens` data class that explains what it is?
  

## Questions

- There are many seemingly aribitrary values. For instance, the `Dimens` data class; or in `Theme.kt` there is the following line of code `if (config.screenWidthDp <= 360)`. I just wonder where does all of these values come from.
  

## Steps before merge

- Add the KDoc comment above the `Dimens` data class.

2024-11-03 21:58 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/theme/Dimens.kt
> +data class Dimens(
This is an initial setup for screen responsiveness. I'll adapt and fine-tune the paddings as I integrate them into the screens. Depending on the specific requirements, some paddings may need to be added or removed.

The main approach involves retrieving the screen size and applying a suitable padding set based on the device's width. This helps categorize devices into compact (S, M, L), medium, or extended, adjusting both padding and typography sizes to fit different screens effectively.

An alternative, though more precise, method would calculate proportional padding for each component (e.g., 24dp out of 418dp equals xx% of width). This would involve applying padding as a percentage of the display's width. However, it sacrifices readability and makes typography sizing harder to adapt and maintain.

2024-11-03 21:59 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/theme/Theme.kt
> +  Toast.makeText(LocalContext.current, dims, Toast.LENGTH_SHORT).show()
My bad, I forgot. I just used it to know what kind of device I was running xD

2024-11-03 22:08 UTC, francelu commented
@lazarinibruno  
Regarding your question about the seemingly arbitrary values, I'd watched a [video](https://www.youtube.com/watch?v=Dj_X-RKL-c0) where these values were used. If you'd prefer, I can adjust them or convert them into vals for better clarity and consistency. Let me know your thoughts!

2024-11-03 22:15 UTC, lazarinibruno commented on app/src/main/java/com/android/periodpals/ui/theme/Dimens.kt
> +data class Dimens(
Perfect! Thanks for clarifying:)

2024-11-03 22:16 UTC, lazarinibruno commented
> @lazarinibruno  
> Regarding your question about the seemingly arbitrary values, I'd watched a [video](https://www.youtube.com/watch?v=Dj_X-RKL-c0) where these values were used. If you'd prefer, I can adjust them or convert them into vals for better clarity and consistency. Let me know your thoughts!

It's perfect the way it is, I just wanted to understand!

2024-11-03 22:16 UTC, lazarinibruno approved these changes

2024-11-03 22:18 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/theme/Dimens.kt
> +data class Dimens(
You're welcome !

2024-11-04 07:48 UTC, merged