feat/authentication/cleanup : Clean up code from M1 : `ui.authentication` package
PeriodPals/periodpals pull request #125
Opened 2024-11-02 20:04 UTC by charliemangano

# Clean up code from M1 : `ui.authentication` package

## Description
This PR introduces code cleanup and new documentation for the files in package `ui.authentication`, including corresponding tests. It closes issue #124 and part of #84.

## Changes

## Files 
#### Added
None
#### Modified
- 
#### Removed
None
## Dependencies Added
None

## Testing
All tests still pass.

2024-11-05 13:30 UTC, lazarinibruno commented on app/src/main/java/com/android/periodpals/ui/authentication/SignIn.kt
> +private fun attemptSignIn(
I find that the code inside this function is hard to read, given the multiple nested if statements.

2024-11-05 13:46 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/ui/authentication/SignIn.kt
> +private fun attemptSignIn(
I'll try and take care of that, thanks for pointing it out! Same remark for `attemptSignUp` in `SignUp.kt` or is that one okay?

2024-11-05 14:41 UTC, lazarinibruno requested changes
## Summary

Thanks for your contribution!

- Very good job on decreasing the duplication of code.
  
- Improves mainteinance by extracting constant values.
  

## Improvements

In `SignIn.kt` I would refactor the `attemptSignIn` function to something like:

```kotlin
if (!isEmailValid(email, setEmailErrorMessage) || 
    !isPasswordValid(password, setPasswordErrorMessage) {
    return { Toast.makeText(context, INVALID_ATTEMPT_TOAST, Toast.LENGTH_SHORT).show() }
}

// Attempt log in
authenticationViewModel.logInWithEmail(email, password)
authenticationViewModel.isUserLoggedIn()


return {
    val loginSuccess = userState is UserAuthState.Success
    if (loginSuccess) {
        Toast.makeText(context, SUCCESSFUL_SIGN_IN_TOAST, Toast.LENGTH_SHORT).show()
        navigationActions.navigateTo(Screen.PROFILE)
    } else {
        Toast.makeText(context, FAILED_SIGN_IN_TOAST, Toast.LENGTH_SHORT).show()
    }
}
```

## Steps before merge

Just the modification I suggested. Otherwise, code LGTM.

2024-11-06 10:28 UTC, agonzalez-r approved these changes
Code is consistent and much more clean. 
Thank you for this hard work! 

LGTM

2024-11-07 13:04 UTC, lazarinibruno approved these changes
Code is much readable now!

2024-11-08 15:11 UTC, merged