Test/misc/edit button visibility
PeriodPals/periodpals pull request #127
Opened 2024-11-03 11:07 UTC by francelu

# Enhance UI Tests and Update Top Bar Titles

## Description
This PR enhances UI tests across multiple screens by adding assertions for component visibility and text content, and updates top bar titles for consistency. It closes issue #126.

## Changes

### Enhancements to UI Tests
- Added assertions for component visibility and text content in the following test classes:
  - `AlertListScreenTest`
  - `AlertScreenTest`
  - `MapScreenTest`
  - `CreateProfileTest`
  - `ProfileScreenTest`
  - Introduced `TimerScreenTest` to check components visibility.

### Updates to Top Bar Titles
- Changed titles to ensure consistency:
  - "Alert Lists" for `AlertsList`
  - "Map" for `Map`
  - "Create Your Account" for `CreateProfile`
  - "Your Profile" for `ProfileScreen`
  - "Tampon Timer" for `TimerScreen`

## Files 

#### Added
- `app/src/androidTest/java/com/android/periodpals/ui/timer/TimerScreenTest.kt`

#### Modified
- `app/src/androidTest/java/com/android/periodpals/ui/alert/AlertListScreenTest.kt`
- `app/src/android/periodpals/ui/alert/AlertScreenTest.kt`
- `app/src/android/periodpals/ui/map/MapScreenTest.kt`
- `app/src/android/periodpals/ui/profile/CreateProfileTest.kt`
- `app/src/android/periodpals/ui/profile/ProfileScreenTest.kt`
- `app/src/main/java/com/android/periodpals/ui/alert/AlertsList.kt`
- `app/src/main/java/com/android/periodpals/ui/map/Map.kt`
- `app/src/main/java

2024-11-03 11:13 UTC, coaguila approved these changes
Lgtm

2024-11-03 11:42 UTC, charliemangano requested changes
## Summary
Nice job! I left some notes in the comments.
## Important 
#### Code Quality
Good work making the app consistent with the Figma! Please refactor the screen titles to make the code more maintainable and consistent (see comments)
#### Functionality
Code is correct
## Testing
Tests pass and are complete
## Documentation
See comments
## Suggestions
See comments
## Steps before PR approved
See comments

2024-11-03 11:42 UTC, charliemangano commented on app/src/androidTest/java/com/android/periodpals/ui/alert/AlertListScreenTest.kt
Nice job finding this inconsistency!

2024-11-03 11:42 UTC, charliemangano commented on app/src/androidTest/java/com/android/periodpals/ui/map/MapScreenTest.kt
> +    `when`(navigationActions.currentRoute()).thenReturn(Route.ALERT)
```suggestion
    `when`(navigationActions.currentRoute()).thenReturn(Route.MAP)
```

2024-11-03 11:42 UTC, charliemangano commented on app/src/androidTest/java/com/android/periodpals/ui/map/MapScreenTest.kt
>  // UI test for MapViewContainer.kt
this comment is redundant, can you remove it?

2024-11-03 11:42 UTC, charliemangano commented on app/src/androidTest/java/com/android/periodpals/ui/map/MapScreenTest.kt
>      // Verify that the map is displayed when permission is granted
This comment could be removed if renaming the test `checkMapIsDisplayedWhenPermissionGranted`
This makes the code self-documenting and the tests more explicit

2024-11-03 11:42 UTC, charliemangano commented on app/src/androidTest/java/com/android/periodpals/ui/map/MapScreenTest.kt
>      // Verify that the map is still displayed even if permission is not granted
this comment could be removed if renaming the test `checkMapIsDisplayedWhenNoPermissions`
As before, this makes the code self-documenting

2024-11-03 11:42 UTC, charliemangano commented on app/src/androidTest/java/com/android/periodpals/ui/map/MapScreenTest.kt
>        PeriodPalsAppTheme {
The call to `PeriodPalsAppTheme` is redundant here, as that's not what we are testing for. 
Same in other functions

2024-11-03 11:42 UTC, charliemangano commented on app/src/androidTest/java/com/android/periodpals/ui/profile/CreateProfileTest.kt
As in the `MapScreenTest` file, setting the theme is not necessary. Plus here the theme used is the Material one and not our `PeriodPalsAppTheme`.
I saw this file has not been cleaned up yet so I don't know that it's your job to fix this?

2024-11-03 11:42 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/ui/map/Map.kt
> +      topBar = { TopAppBar(title = "Map") },
"Map" should be extracted to a `private const val SCREEN_TITLE` for better maintainability and readability.

2024-11-03 11:42 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/ui/alert/AlertsList.kt
> +          TopAppBar(title = "Alert Lists")
Thanks for changing this! 
It should be extracted to a `private const val SCREEN_TITLE` for better maintainabilty.

2024-11-03 11:42 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/ui/profile/CreateProfile.kt
> +      topBar = { TopAppBar(title = "Create Your Account") },
This should be extracted to a `private const val` as well

2024-11-03 11:42 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/ui/profile/ProfileScreen.kt
> +            title = "Your Profile",
This should be extracted to a `private const val` as well

2024-11-03 11:42 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/ui/timer/Timer.kt
> +      topBar = { TopAppBar(title = "Tampon Timer") },
This should be extracted to a `private const val` as well

2024-11-03 18:31 UTC, francelu commented on app/src/androidTest/java/com/android/periodpals/ui/map/MapScreenTest.kt
> +    `when`(navigationActions.currentRoute()).thenReturn(Route.ALERT)
Fixed !

2024-11-03 18:32 UTC, francelu commented on app/src/androidTest/java/com/android/periodpals/ui/map/MapScreenTest.kt
>  // UI test for MapViewContainer.kt
Sure !

2024-11-03 18:34 UTC, francelu commented on app/src/androidTest/java/com/android/periodpals/ui/map/MapScreenTest.kt
>      // Verify that the map is displayed when permission is granted
Removed and renamed !

2024-11-03 18:34 UTC, francelu commented on app/src/androidTest/java/com/android/periodpals/ui/map/MapScreenTest.kt
>      // Verify that the map is still displayed even if permission is not granted
Removed and renamed !

2024-11-03 18:36 UTC, francelu commented on app/src/androidTest/java/com/android/periodpals/ui/map/MapScreenTest.kt
>        PeriodPalsAppTheme {
Removed unnecessary call to `PerioPalsAppTheme`.

2024-11-04 11:13 UTC, charliemangano approved these changes
LGMT! Thank you for implementing the changes!

2024-11-04 11:16 UTC, merged