Fix/profile/create profile UI tests: Fix UI tests fro CreateProfile
PeriodPals/periodpals pull request #139
Opened 2024-11-06 12:16 UTC by agonzalez-r

# Fix UI tests for CreateProfile

## Description
This PR closes issue #74 and #63, by fixing tests for the `CreateProfile` screen. 

## Changes

## Files 
#### Modified
- `main/.../ui/profile/CreateProfile.kt`: added documentation and removed unused functions. 

## Testing
- `androidTests/.../ui/profile/CreateProfileTest`: ensured proper and complete testing of the verification of validity for all fields as well as the correct functionality of the navigation actions.

2024-11-06 12:42 UTC, Harrish92 approved these changes
## Summary
Good job on making the code easier to read.

#### Code Quality
- The comments provide great insights about the code.

## Suggestions
- Remove unnecessary empty lines in `ProfileScreenTest` functions

## Steps before PR Merge
- Implement the suggestion mentioned above

2024-11-06 20:53 UTC, francelu requested changes
## Summary
Improves profile creation tests for consistency and refines `ProfileScreen` layout.

## Minor Issue
- The screen doesn’t exactly match the Figma, but this will be managed in a separate task. This isn't blocking further work on implementing the VM for profile screens.

## Steps before PR Approval
- Address all in-line comments.
- Rename tests and make adjustments as per file-specific comments.

2024-11-06 20:53 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/profile/CreateProfile.kt
> +    name.isEmpty() -> "Please enter a name"
- First check move the name's line up by 1. That's how components are displayed.
- Refractor `date` to `dob` to be consistent across screens.

2024-11-06 20:53 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/profile/CreateProfile.kt
Please address the changes mentioned in the in-line comment, and the following ones:
- Lines 91-113, lines 114-126, lines 144-155: I don't see why the `Box` components are necessary. We implemented the `GlideImage` by itself in the `ProfileScreen`.
- Please add comments in the code to describe what the components are, i.e. `// User profile's image` and more.
- L.186: why padding of 0 ?

2024-11-06 20:53 UTC, francelu commented on app/src/androidTest/java/com/android/periodpals/ui/profile/CreateProfileTest.kt
- You aren't checking that the "section field" for "Mandatory" and "Your Profile" are displayed.
- Check that for the bottom navigation `assertDoesNotExist()`.
- Please use a companion object to fill in the fields in your tests. See our other tests for reference.
- Please rename your test as `createValidProfile()`, `createInvalideProfileNoEmail()`, ... for consistency with our other tests' naming convention. For example, see the `CreateAlertScreenTest`.
  In these same tests, we didn't necessarily test that the components for `assertIsDisplayed()`. You could remove these checks for better code readability.

2024-11-06 21:12 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/ui/profile/CreateProfile.kt
> +    name.isEmpty() -> "Please enter a name"
Not sure what you mean, I changed the order of the checks to match the order of the fields: 
<img width="386" alt="Screenshot 2024-11-06 at 22 10 00" src="https://github.com/user-attachments/assets/bf8e5534-0783-41d8-b650-efda368a4c09">

2024-11-06 21:18 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/ui/profile/CreateProfile.kt
I'll add the comments for better readability but not sure if we want to modify the padding/ui in this task, it was not the purpose. For the issue #63 we focus more on correcting the tests and adding missing components to the screen (if missing) to test their display. So although there are some things to fix to match the UI of the Figma, all the correct components are displayed.

2024-11-06 21:27 UTC, agonzalez-r commented on app/src/androidTest/java/com/android/periodpals/ui/profile/CreateProfileTest.kt
Thanks for pointing out the missing checks, I'll make sure to add them!
However I don't agree that the renaming you're proposing is a convention among all of our tests... I think it's a little farfetched. but sure i'll change them

2024-11-06 21:43 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/profile/CreateProfile.kt
> +    name.isEmpty() -> "Please enter a name"
Well :
- For the first point, my bad, this doesn't fit to the Figma yet. So don't worry about move some line.
- However for the second point, the variable is named after `date` while it should be `dob` as we called it in all other screens implementation.

2024-11-06 21:45 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/profile/CreateProfile.kt
Okay, I see your point. Then, just do the comments and remove the (I think) useless `.padding(0.dp)`.

2024-11-07 10:15 UTC, francelu requested changes
Just a few nitpicks mentioned in the file reviews.

2024-11-07 10:15 UTC, francelu commented on app/src/androidTest/java/com/android/periodpals/ui/profile/CreateProfileTest.kt
Good implementation of the changes.  
Please remove the in-line code comments and useless spaces as they aren't relevant.

2024-11-07 10:15 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/profile/CreateProfile.kt
The `Box` components are still not very useful around the section texts.  
You could have changed it to the modifier of the text to `fillMaxWidth()`, and `textAlign = TextAlign.left`  or sth so.

2024-11-07 13:10 UTC, francelu approved these changes
Perfect ! LGTM !  
Thanks for doing these changes to keep a clean code :))

2024-11-07 13:17 UTC, merged