Feat/alert/model impl: Create AlertModelSupabase
PeriodPals/periodpals pull request #143
Opened 2024-11-07 14:58 UTC by agonzalez-r

# Feat/alert/model-impl: Implementation of the Alert model with supabase

## Description
This PR introduces the class implementation (`AlertModelSupabase`) of the previously done model interface (`AlertModel`), using supabase as the database. 

I have some doubts about this implementation and the model in general, some of them are: 
- do we really need to declare the parameters `id` and `uid` in the data class `Alert`? or should these values be managed directly by supabase ? 
- should we add a function `getMyAlerts(uid, ...)`, giving the `uid` as parameter and selecting all alerts linked to that uid 

## Changes

## Files 

#### Added
- `main/.../model/alert/AlertModelSupabase`: implementation of all the functions defined in the interface 
#### Modified
- `main/.../model/alert/AlertModelSupabase`: had to add a parameter `idAlert` in the `updateAlert()` function to be able to identify which alert to modify 

## Testing
Not possible at the moment (View Model will be tested)

2024-11-07 15:00 UTC, coaguila commented on app/src/main/java/com/android/periodpals/model/alert/AlertModelSupabase.kt
> +      onSuccess: () -> Unit,
you could return the alertId here

2024-11-07 15:03 UTC, coaguila commented on app/src/main/java/com/android/periodpals/model/alert/AlertModelSupabase.kt
> +      onSuccess(result)
Don't forget to add `Log.d` before `onSuccess` to help debugging later on.

2024-11-07 17:48 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/model/alert/AlertModelSupabase.kt
> +      onSuccess: () -> Unit,
That makes sense in the case where the idAlert is defined once it is stored in supabase but right now it is a part of the data class so the parameter `alert` that is passed to the function should already have an idAlert, possibly generated in the view model, right? 

I think it really depends on the implementation but it is one of the questions I asked in the PR description, did you take a look at them?

2024-11-07 17:56 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/model/alert/AlertModelSupabase.kt
> +      onSuccess: () -> Unit,
or maybe we can turn the parameter nullable `val id: String? = ""` so that when the alert is created, we leave this value empty and the id is created directly in supabase, but still accessible through the data class?

2024-11-09 22:17 UTC, agonzalez-r commented
# Feat/alert/model-impl: Implementation of the Alert model with supabase
## Description
This PR closes issue #117 by implementing and testing the functions declared in the interface `AlertsModel`. It also fixed some issues with the data class declaration, after further investigation about the proper methodology.

For better understanding of why some values in the `Alert` data class are nullable, check the table in supabase and their corresponding default values (some values are filled while the instance is created in supabase). 
## Changes
## Files 
#### Added
- `model/alert/AlertDto.kt`: data transfer object which is a serializable version of `Alert.kt`. This type of object is the one used for interacting with the repository, while the normal data class is used for UI usability. 

#### Modified
- `model/alert/Alert.kt`: made non-serializable, changed the type of some values (specially `createdAt` value was converted to string because of conflicts with "serializing" `LocalDateTime`)
- `model/alert/AlertModelSupabase`: ensured proper use of the `AlertDto` data class when calling repository functions and also did proper conversion to `Alert` when the functions had values to return. 
 
## Testing
- `test[UnitTest]/.../model/alert/AlertModelSupabaseTest`: tests for both success and failure (mocked) supabase responses to all the functions of the model.

2024-11-10 00:29 UTC, charliemangano requested changes
**WIP sorry je vais dodo mais j'ai peur que ça s'enregistre pas mdr**

> do we really need to declare the parameters id and uid in the data class Alert? or should these values be managed directly by supabase ?

I'm leaving this question to @coaguila, he'll know much more about this.

> should we add a function getMyAlerts(uid, ...), giving the uid as parameter and selecting all alerts linked to that uid

No, this should be done in the view mode. The model should stay as agnostic as possible of what is happening in the rest of the app. However, we can have a `getAlertsFilteredBy` function taking a `(Alert) -> Boolean` lambda as parameter. This would let the view model handle the actual logic but would make the model much more usable while still staying agnostic.

good job updating the docs
make sure to delete comments and TODOs, or to explicit them. Comments should be about the why not the how, and TODOs should be converted to issues or tasks.

2024-11-10 00:29 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/model/alert/AlertModelSupabase.kt
> +              .select { filter { eq("id", idAlert) } }
What is the `eq` here? Does normal structural equality `==` not work?

2024-11-10 00:29 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/model/alert/AlertModelSupabase.kt
> +  }
See `AlertModel` interface for my comment on this

2024-11-10 00:29 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/model/alert/AlertModelSupabase.kt
> +                status = alert.status)
Here too you can use the `AlertDto` constructor.

2024-11-10 00:29 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/model/alert/AlertModelSupabase.kt
> +          filter { eq("id", alert.id) }
Here as well, why the `eq`

2024-11-10 00:29 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/model/alert/AlertModelSupabase.kt
> +      supabase.postgrest[ALERTS].delete { filter { eq("id", idAlert) } }
Again, `eq`?

2024-11-10 00:29 UTC, charliemangano commented on app/src/test/java/com/android/periodpals/model/alert/AlertModelSupabaseTest.kt
> +  companion object {
Weird mix of snake case and camel case ●﹏●

2024-11-10 00:29 UTC, charliemangano commented on app/src/test/java/com/android/periodpals/model/alert/AlertModelSupabaseTest.kt
> +import com.android.periodpals.model.alert.Alert
Very complete tests, and very clean code as well, good job!

2024-11-10 09:34 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/model/alert/Alert.kt
>  /** Enum class representing the product requested with the alert. */
Yes that's true!

2024-11-10 09:37 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/model/alert/AlertModel.kt
> +   * @param alert Updated parameters for the Alert, id must not be null to know which alert to
I wanted to specify that it is the **alert with the updated parameters** that you need to pass as argument. And since to find which alert it is we need its `id`, we need that to be non-null inside the Alert. 
Could you propose a better way of describing this?

2024-11-10 09:39 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/model/alert/AlertModelSupabase.kt
> +                status = alert.status)
That's right! forgot to use it

2024-11-10 09:40 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/model/alert/AlertModelSupabase.kt
> +          filter { eq("id", alert.id) }
because we need to apply that only on that specific alert (with `id` == `alert.id`). Without the `eq` it applies that to all alerts in the table

2024-11-10 09:42 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/model/alert/AlertModelSupabase.kt
> +      supabase.postgrest[ALERTS].delete { filter { eq("id", idAlert) } }
It's the only way to specify which alert.

2024-11-10 09:46 UTC, agonzalez-r commented on app/src/test/java/com/android/periodpals/model/alert/AlertModelSupabaseTest.kt
> +  companion object {
Yes I followed it to be consistent with the other model unit tests :( like `AuthenticationModelSupabaseTest`, I just realised it's not the case for `UserModelSupabaseTest`

2024-11-10 09:47 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/model/alert/AlertModel.kt
> +  )
Okay, I can change that !

2024-11-10 10:53 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/model/alert/AlertModelSupabase.kt
> +      supabase.postgrest[ALERTS].delete { filter { eq("id", idAlert) } }
Oh yes you're right, I finally found the docs for it this morning

2024-11-10 10:56 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/model/alert/AlertModel.kt
> +   * @param alert Updated parameters for the Alert, id must not be null to know which alert to
I'd say something along the lines of:
```suggestion
   * @param alert Alert with updated parameters. `id` must not be null to know which alert to
```

2024-11-10 11:20 UTC, coaguila approved these changes
Lgtm

2024-11-10 13:39 UTC, charliemangano approved these changes
LGTM! Thanks for implementing the points I had highlighted.

2024-11-10 13:39 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/model/alert/AlertModelSupabase.kt
> +  }
Good generalisation of old `getMyAlerts` into `getAlertsFilteredBy`, thanks for implementing my comment suggestion!

2024-11-10 13:49 UTC, merged