Feat/alert/simple location dropdown
PeriodPals/periodpals pull request #167
Opened 2024-11-10 10:34 UTC by taghizadlaura

# Add a dropdown menu component to the Location field in the CreateAlert screen

## Description
This PR introduces a dropdown menu to the Location field in the `CreateAlert` screen. The dropdown menu provides location suggestions as the user types, making it easier to select a location from a prepopulated list of suggestions. This update enhances the user experience by allowing users to see location options that match their query input. It closes issue #152.

## Changes
- Added a dropdown menu using `ExposedDropdownMenuBox` and `ExposedDropdownMenu` for displaying location suggestions.
- Integrated the `locationViewModel` to provide location suggestions based on user input in the Location field.
- Added an option to display additional locations with a "More..." item when there are more than three suggestions.

## Files 

### Added
- `LocationRepository.kt` - Handles location data retrieval.
- `LocationViewModel.kt` - Manages location-related state, including user input and query results.
- `NominatimLocationRepository.kt` - Uses the Nominatim API to fetch location data.

### Modified
- `CreateAlertScreen.kt` - Added dropdown menu functionality to the Location field.

### Removed
No files were removed.

## Dependencies Added
- `implementation(libs.okhttp)` - For HTTP requests to the Nominatim API.

## Testing
- Manual testing of the dropdown menu to ensure it appears correctly when typing in the Location field.
- Verified that the "More..." option appears if more than three location suggestions are available.
- Tested that selecting a location from the dropdown updates the `Location` field and query.

## Screenshots 
### Empty Dropdown
<img src="https://github.com/user-attachments/assets/915aa861-27cb-40f3-aa8b-335dd8fe1a16" alt="DropDownLocationEmpty" width="300"/>

### Typing in Dropdown
<img src="https://github.com/user-attachments/assets/b3f6e740-1484-4c45-a17f-a8ab59bc822f" alt="DropDownLocationEnter" width="300"/>

### Dropdown with Location Suggestions for "EPFL"
<img src="https://github.com/user-attachments/assets/4657ff0d-5889-4aa1-8288-050fe36fc1ba" alt="DropDownLocationEnterEPFL" width="300"/>

2024-11-11 17:02 UTC, taghizadlaura commented
Thank you, @francelu and @charliemangano, for helping me resolve merge conflicts, fix existing tests, and create more useful ones!

2024-11-11 20:05 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/model/location/LocationModel.kt
> +  fun search(query: String, onSuccess: (List<Location>) -> Unit, onFailure: (Exception) -> Unit)
Add documentation for this function

2024-11-11 20:22 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/model/location/LocationModelNominatim.kt
> +                "User-Agent", "YourAppName/1.0 (your-email@example.com)") // Set a proper User-Agent
Shouldn't we replace 'YourAppName' here ?? seems like a placeholder

2024-11-11 20:23 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/model/location/LocationModelNominatim.kt
> +            .header("Referer", "https://yourapp.com") // Optionally add a Referer
remove this comment (for cleaner code) and also replace placeholder with the name of the app?

2024-11-11 20:37 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/model/location/LocationViewModel.kt
> +  private val query_ = MutableStateFlow("")
nitpick: put underscore at the beginning of the name (it's convention, also to avoid the remark from Android studio)

2024-11-11 20:40 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/model/location/LocationViewModel.kt
> +      repository.search(query, { locationSuggestions_.value = it }, {})
Implement error call back here. Add logs to both `onSuccess` and `onFailure` callback functions

2024-11-11 20:45 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/ui/alert/CreateAlert.kt
> +fun CreateAlertScreen(
update documentation to the screen (added parameter)

2024-11-11 21:17 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/ui/alert/CreateAlert.kt
> +          ExposedDropdownMenu(
In my emulator I have the issue that I have to re-click inside the outlined field for each letter i type, I'm not sure if it's just my emulator. 
I had this problem when I did the bootcamp and I fixed it using `properties = PopupProperties(focusable = false),` as a parameter in `DropDownMenu`, however since here you're using `ExposedDropDownMenu` there is no parameter `properties`. 
If this issue is always present (not just in my emulator), please consider switching to `DropDownMenu` in order to use this property and have a smoother user experience.

2024-11-11 21:42 UTC, agonzalez-r requested changes
## Summary
This PR  effectively implements the Location suggestions in the `CreateAlert` screen. 
Good job on the long work!
## Important (which includes)
#### Code Quality
All good, just a few things to change, look at my comments per line. 
#### Performance (if applicable)
- Look at my comment for `CreateAlert.kt`, the performance of the input of the location (when done manually) is really downgraded by the fact that the focus is drawn away of the input field for each typed letter. 
## Testing
- Good tests! they all pass. 
## Documentation
- Missing documentation for most added files 
- Need to update documentation for some modified files
## Steps before PR approved
- Fix documentation 
- Add missing callback functions in `LocationViewModel`
- Try to change the `ExpandedDropDownMenu` to `DropDownMenu` to fix the bug (have to type letter by letter), improving the experience, don't worry so much about matching the Figma. It's better to have it working properly than matching the UI

2024-11-12 08:18 UTC, taghizadlaura commented on app/src/main/java/com/android/periodpals/ui/alert/CreateAlert.kt
> +          ExposedDropdownMenu(
I know I also had this problem during the bootcamp, but I’m not sure it would be fixed with a DropDownMenu. The implementation I’m using actually comes from the bootcamp solution itself. Also, if you type on the emulator’s keyboard, this issue doesn’t occur... So, I think it might be an emulator-specific problem. Maybe we could try to fix it in another task later, since it’s currently working and we’re not sure what’s causing it?

2024-11-12 08:19 UTC, taghizadlaura commented on app/src/main/java/com/android/periodpals/ui/alert/CreateAlert.kt
> +                  onClick = { /* TODO show more results */},
Yes, I thought it would be better to handle it in another task when we’re ready to upgrade it.

2024-11-12 09:04 UTC, agonzalez-r approved these changes
Thank you fro the changes and clarifications!
LGTM

2024-11-12 09:33 UTC, taghizadlaura commented
@francelu and @charliemangano, since you've helped me with small details in this code, you're already acquainted with it without being biased, so I'm assigning it to you.

2024-11-12 10:49 UTC, lazarinibruno approved these changes
## Summary
Thank you for your work! It is cool finally have the possibility to link the alerts with a geographical location 🌍📍.

## Important

### Code Quality
- Code is readable, well-structured and clean.
- As I mentioned in the comments, there are some "magic numbers" that can be extracted to `private const val`.

### Functionality
**Question**: Maybe I missed a part in the code, but I could not find where do you store the location that the user selects in the drop-down menu. 

## Testing
Overall good testing. 

## Documentation
You did a great job documenting the code! Classes, functions and composables have docs using keywords such as `@param.`  

With respect to comments, adding some explanatory comments in the code would have made the review a tad easier. For instance, in `LocationModelNominatim.kt` on line 82:
 
```kotlin
client
    .newCall(request)
    .enqueue(
        ...
```
It took me a while to get what this is doing. I know that we did this in the Bootcamp, but still it wasn't fresh in my mind. In the future, consider writing more comments.
 
## Suggestions
Besides the nitpicks, code looks great!

## Steps before PR approved
LGTM 🤠

2024-11-12 10:49 UTC, lazarinibruno commented on app/src/main/java/com/android/periodpals/model/location/LocationViewModel.kt
> +  private var locationSuggestions_ = MutableStateFlow(emptyList<Location>())
**Nitpick**: I believe @agonzalez-r already mentioned it, but the convention is to write the underscore `_` before the name of the variable.

2024-11-12 10:49 UTC, lazarinibruno commented on app/src/main/java/com/android/periodpals/ui/alert/CreateAlert.kt
> +                                if (location.name.length > 30) "..." else "", // Limit name length
**Nitpick**: Create a `private const val MAX_NAME_LEN = 30`

2024-11-12 10:49 UTC, lazarinibruno commented on app/src/main/java/com/android/periodpals/ui/alert/CreateAlert.kt
> +            if (locationSuggestions.size > 3) {
**Nitpick**: Same as previous comment, extract it to `private const val`.

2024-11-12 11:25 UTC, taghizadlaura commented on app/src/main/java/com/android/periodpals/model/location/LocationModelNominatim.kt
> +                "User-Agent", "PeriodPals/1.0 (your-email@example.com)") // Set a proper User-Agent
Yes, it was included in the bootcamp correction, and I didn't remove it in case we want to provide an email to help identify the source of requests for troubleshooting or support purposes. But maybe it's cleaner to remove it for now?

2024-11-12 12:22 UTC, merged