Feat/profile/create
PeriodPals/periodpals pull request #20
Opened 2024-10-10 12:08 UTC by Harrish92

2024-10-10 14:16 UTC, francelu requested changes
### First of all
I love the hippopotamus profile picture!

### Important
Please ensure to run the following on all files you’ve modified:
- **Optimize Imports**
- **Reformat Code**
- **Code Cleanup**
- **Run `gradle ktfmt`**

### File Review
- **`app/build.gradle.kts`**: LGTM.
  
- **`AndroidManifest.xml`**: LGTM.
  
- **`MainActivity.kt`**: 
  - Keep `CountriesList()` and remove unnecessary imports. Please run **Optimize Imports**.
  - Ensure to run **ktfmt** on this file as well.

- **`User.kt`**: 
  - Remove the `{}` at the end of the `data class` definition.

- **`CreateProfile.kt`**:
  - Ensure to **Optimize Imports**, **Reformat Code**, perform **Code Cleanup**, and run **ktfmt**.
  - The input field labelled "Age" may cause confusion, as it is unclear whether the user is expected to enter their age or their date of birth. It would be beneficial to rename this field to "Date of Birth" to provide clarity. Additionally, please specify the required format (e.g., "Enter your date of birth in DD/MM/YYYY format") to guide users effectively.

- **`Theme.kt`**: 
  - Consider uncommenting the other colours for overriding. These will likely be redefined in Sprint 2.

- **`generic_avatar.png`**: LGTM.  
- **`roboto.xml`**: 
  - I don’t see the purpose of this file, as it doesn’t seem to be referenced anywhere. Could you clarify its necessity for the project?

- **`libs.versions.toml`**: LGTM. 

### Additional Notes
- **Missing Tests**: It appears that UI tests for the Create Profile screen are missing. Please refer to the tests for `AddToDoScreen` in the bootcamp for guidance on how to implement these.

2024-10-13 12:07 UTC, francelu reviewed
### Improvements
Please address the following points real quick:

1. **Date Validation Logic**:
   - The date validation logic should be extracted into a separate function to enhance readability and facilitate easier testing.

2. **Test Assertions**:
   - Add assertions in `testSaveButtonClickWithValidDate` and `testSaveButtonClickWithInvalidDate` to verify the application's behavior after clicking the save button. This will ensure that the date input is handled correctly and that appropriate feedback is provided to the user.  

Otherwise, LGTM.

2024-10-13 17:00 UTC, Harrish92 commented
### Improvements

I have addressed the following points:

#### Date Validation Logic:
The date validation logic has been extracted into a separate function to enhance readability and facilitate easier testing.

#### Test Assertions:
Added assertions in `testSaveButtonClickWithValidDate` and `testSaveButtonClickWithInvalidDate` to verify the application's behavior after clicking the save button. This ensures that the date input is handled correctly and that appropriate feedback is provided to the user.

2024-10-13 17:16 UTC, francelu approved these changes
LGTM. :)

2024-10-13 17:16 UTC, francelu commented on app/src/main/AndroidManifest.xml
> +            android:name="com.android.periodpals.MainActivity"
You don't need to specify `com.android.periodpals.MainActivity`. In the authentication UI branch, I ran `MainActivity` with just `.MainActivity` while the emulator was on.  
Your version may work as well, so let’s stick with it for now. :))

2024-10-13 17:16 UTC, francelu commented on app/src/main/java/com/android/periodpals/MainActivity.kt
> +          // CountriesList()
It’s better to keep CountriesList() here to avoid merging incomplete screens into the main branch.  
Once we merge the navigation, this issue will be resolved. For now, let's leave it as is.

2024-10-13 18:06 UTC, coaguila approved these changes
LGTM

2024-10-13 18:10 UTC, merged