Feat/profile/implement delete account function
PeriodPals/periodpals pull request #213
Opened 2024-11-18 20:15 UTC by Harrish92

# Title
feat: implement delete account function

## Description
This PR introduces the functionality to delete a user account. It closes issue #212 .

## Changes
- Added `deleteUser` method in `UserViewModel` to handle account deletion.
- Implemented `deleteUserProfile` method in `UserRepositorySupabase` for Supabase integration.
- Added unit tests for `deleteUserProfile` in `UserRepositorySupabaseTest`.
- Updated `UserViewModelTest` with tests for account deletion.

## Files 

#### Added
- `app/src/test/java/com/android/periodpals/model/user/UserRepositorySupabaseTest.kt`

#### Modified
- `app/src/main/java/com/android/periodpals/model/user/UserViewModel.kt`
- `app/src/main/java/com/android/periodpals/model/user/UserRepositorySupabase.kt`
- `app/src/main/java/com/android/periodpals/model/user/UserRepository.kt`

## Testing
- Unit tests for `deleteUserProfile` method in `UserRepositorySupabaseTest`.
- Unit tests for `deleteUser` method in `UserViewModelTest`.

2024-11-19 14:09 UTC, charliemangano requested changes
## Summary
The code you wrote is consistent with the rest of the codebase and very clear. However, you did not implement the correct function: what you wrote deletes all entries in the `users` table, not a specific user. See code comments.

## Important (which includes)
#### Code Quality
Code is consistent and readable, good job!
#### Functionality
As said in the summary and the comments, `UserModelSupabase.deleteUserProfile` deletes all entries in the Supabase table, when we would like it to delete only the current user! See comments for recommendations. 
## Testing
The `UserViewModel` and `UserModel` tests are update to account for the new method.Since in `UserModelSupabaseTest` we can only verify that it calls the correct callback, and in `UserViewModelTest` we have to mock the model, it's normal that you missed the error. Maybe we should put someone on thinking about how we could test this remaining part of it.
## Documentation
Good documentation added to `UserModel`. Remember to update it if you end up changing the method's signatures!
## Suggestions
See comments.
## Steps before PR approved
You need to implement the filter on the `deleteUserProfile` method, or find another Supabase method alltogether, to remove only one, chose user at a time.

2024-11-19 20:51 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/model/user/UserModelSupabase.kt
> +  }
We do not want Supabase to handle this, it should be logic we handle ourselves. Giving it to Supabase will just give us less control over how we handle our data.

Supabase would most likely also return an error without finishing the task, so it would make our error handling useless and the function unusable. Please revise the requested changes.

2024-11-20 21:37 UTC, Harrish92 commented on app/src/main/java/com/android/periodpals/model/user/UserModelSupabase.kt
> +  }
I added `idUser` parameter to the signature to keep the consistency with `AlertModelSupabase`. Now the users are filtered by the id that is given to the `deleteUserProfile` method.

2024-11-21 09:16 UTC, charliemangano approved these changes
LGTM, thanks for implementing the changes and updating the docs and tests accordingly.
I have a question in the comments (sorry for not noticing it the last time around)

2024-11-21 09:16 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/model/user/UserViewModel.kt
> +      try {
Sorry I didn't see it the last time around, but why do you surround the call to `deleteUserProfile` (that does not throw) with a `try-catch`? It seems redundant and complexifies the code for no reason, since we already handle exceptions in the called function and in the callbacks.

2024-11-21 09:16 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/model/user/UserModelSupabase.kt
> +        supabase.postgrest[USERS].delete() { filter { eq("user_id", idUser) } }
Good implementation of the filter to delete only one user! Thanks for updating it!

2024-11-21 11:32 UTC, Harrish92 commented
> Perhaps create a new data class where we store sensitive issue to be shared to all view models.

@coaguila
Done. `SharedData` is the data class where these issues are going to be stored.

2024-11-21 11:47 UTC, merged