Feat/timer/view model
PeriodPals/periodpals pull request #225
Opened 2024-11-21 13:08 UTC by francelu

# Title
PR is WIP

## Description
This PR introduces... It closes issue #...

## Changes

## Files 

#### Added
- file 1
- file 2
- ...
#### Modified

#### Removed

## Dependencies Added
- dependency 1 for XXX
- ...

## Testing

## Screenshots (if applicable)

2024-11-21 13:15 UTC, francelu commented
How the flow should be :
1. Timer UI: user taps on "Start", "Stop" or "Cancel" button.
2. Timer VM: receives start/stop/cancel event, then calls the corresponding method in `TimerManager`
3. `TimerManager`: starts / stops the `TimerService` and updates the `LiveData` (`timerState`)
4. `TimerService`:  runs in the background calculating elapsed time and periodically notifying `TimerManager` or `ViewModel`
5. UI update: VM updates UI via `LiveData`, s.t. timer display reflects timer state.

2024-11-26 14:46 UTC, coaguila commented on app/src/main/java/com/android/periodpals/model/timer/TimerModelSupabase.kt
> +  }
This is perhaps correct use of Supabase's `delete` function but perhaps a more correct version would come if we added an id to `Timer` & `TimerDto` and added a filter just like the [Supbase docs](https://supabase.com/docs/reference/kotlin/delete) recommend.

Something like this:
```suggestion
  override suspend fun deleteTimer(
      timerID: String, 
      onSuccess: (TimerDto) -> Unit, 
      onFailure: (Exception) -> Unit
  ) {
    try {
      withContext(Dispatchers.Main) {
        supabaseClient.postgrest[TIMERS].delete { 
          filter {
            eq("id", timerId)
          }
        }
        Log.d(TAG, "deleteTimer: Success")
        onSuccess(result)
      }
    } catch (e: Exception) {
      Log.d(TAG, "deleteTimer: fail to delete timer: ${e.message}")
      onFailure(e)
    }
  }
```

2024-11-26 14:48 UTC, coaguila commented on app/src/main/java/com/android/periodpals/model/timer/TimerModel.kt
> +  suspend fun deleteTimer(onSuccess: (TimerDto) -> Unit, onFailure: (Exception) -> Unit)
Just adding to the suggestion in `TimerModelSupabase` : 
```suggestion
  suspend fun deleteTimer(timerID: String, onSuccess: (TimerDto) -> Unit, onFailure: (Exception) -> Unit)
```

2024-11-26 14:56 UTC, coaguila commented on app/src/test/java/com/android/periodpals/model/timer/TimerViewModelTest.kt
> +// }
Plesase remove commented out code! If it is code you need for later you can get it later from git.

2024-11-26 14:59 UTC, coaguila commented on app/src/test/java/com/android/periodpals/model/timer/TimerViewModelTest.kt
Don't forget to add the roboelectric tags for View Model Test, don't hesitate to ask @charliemangano for help on how to add it to your tests.

2024-11-26 15:02 UTC, coaguila commented on app/src/test/java/com/android/periodpals/model/timer/TimerViewModelTest.kt
> +  }
Look into adding `verify` from Mockito, it allows us to test if the mocked function is called correctly with the correct parameters. Check some of the other tests.

2024-11-26 15:11 UTC, coaguila commented on app/src/main/java/com/android/periodpals/model/timer/TimerViewModel.kt
> +  }
So cool! I didn't know that there was `VisibleForTesting` annotation, this will be very useful in future development!

2024-11-26 15:47 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/timer/TimerModelSupabase.kt
> +  }
Okay. I had thought about that. However, since in the RLS policies, a user is only allowed to insert, select, update, delete the timer linked to its uid, I thought we wouldn't need it. Sure I can do the changes ! :)

![image](https://github.com/user-attachments/assets/f733268d-bc6f-4adf-a122-c07778f2b984)

2024-11-26 15:49 UTC, francelu commented on app/src/test/java/com/android/periodpals/model/timer/TimerViewModelTest.kt
> +// }
Ohhhh my bad, I really just forgot to remove it ahaha xD  
Good you noticed !!

2024-11-26 15:50 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/timer/TimerViewModel.kt
> +  }
I think Mistral AI helped me with that one, cause I was in so much despair :')

2024-11-27 13:01 UTC, coaguila requested changes
## Summary
Overall great changes but there are a couple problems. The quality of this code is superb and implementing the `@VisibleForTesting` annotation for testing. Also `TimeManager` functions return values instead of passing them through callbacks.
## Important (which includes)
#### Code Quality
`TimeManager` functions return values instead of passing them through callbacks. Also ` deleteTimer` in `TimerModelSupabase` could have a better implementation of Supabase's delete feature. Other than that, the code is well commented and very readable.
#### Functionality
Perhaps there should be a `getTimers` function for `TimerModel` & `TimerModelSupabase` that could fetch all alerts that could be better than storing all the timers in a string in a json format. Also `deleteTimer` in `TimerModelSupabase` should still take in an ID in case of problems with Supabase RLS. 
## Testing
Perhaps it would be useful to add a couple of `verify` to verify that the parameters are being passed on correctly.
## Documentation
LGTM
## Suggestions
This is great code needs improuvement, there's a couple of quality of life fixes such as not storing all the timers within the latest timer and also bits on commented code that no longer needs to be there.
## Steps before PR approved
- Add `timerID` to `Timer` & `TimerDto`
- Add `userID` to `Timer` & `TimerDto`
- Make `deleteTimer` in `TimerModel` & `TimerModelSupabase` check/filter for ID
- Create `getTimers` that fetches timers for`TimerModel`, `TimerModelSupabase` & `TimerViewModel`

2024-11-27 15:09 UTC, francelu commented on app/src/test/java/com/android/periodpals/model/timer/TimerViewModelTest.kt
Actually, the robolectric thing is just for the UI tests that we put in the unit tests. See this "Note" in [this](https://github.com/PeriodPals/periodpals/pull/208#issue-2668393254) PR description.

2024-11-27 15:21 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/timer/TimerModelSupabase.kt
> +  }
Did the changes !

2024-11-27 15:21 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/timer/TimerModel.kt
> +  suspend fun deleteTimer(onSuccess: (TimerDto) -> Unit, onFailure: (Exception) -> Unit)
Same here :)

2024-11-28 13:56 UTC, coaguila approved these changes
Thanks for implementing the changes, codes lgtm 👍🏽

2024-11-28 15:38 UTC, charliemangano requested changes
## Summary
Nice job with this! The implementation if very complete and well-structured.

## Important
#### Code Quality
The code is dense in functionality but still very readable. Nitpick but you could rename the `...fails` tests to `...Failure` for consistency.
#### Functionality
The code seems correct and passes all the tests, good job!
Take care to run the calls to Supabase within the main thread context in the model (see comments)
## Testing
Very complete testing! However, I don't understand the choice to use the `@VisibleForTesting` annotation instead of simply mocking a functionality, more on this in the comments.
Nitpick since your tests are already complete enough, but you could test for `null` values or extreme timer values, to cover more edge cases. 

## Documentation
Complete and up to date in most places, nicely done! See comments for places I noticed it was missing our outdated.

## Suggestions
See comments.

## Steps before PR approved
Please fix the model (see comments, in particular [this one](TODO)). See comments for nitpicks but I don't consider them necessary to implement before merging. Just make sure to open an issue for anything that you don't do right now.

2024-11-28 15:48 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/timer/TimerManager.kt
> +@VisibleForTesting(otherwise = VisibleForTesting.PACKAGE_PRIVATE)
Uhmm, I think I needed it when I was trying to make the timer stop automatically after 6 hours, for testing purposes. I'll remove it since the tests pass without.

2024-11-28 15:51 UTC, francelu commented on app/build.gradle.kts
> +    viewBinding = true
I though I had needed it, it was from the tutorial the coaches sent.  
I had removed it at one point, and some tests did not pass. But now I think we don't need it. All tests still pass without ! :))

2024-11-28 15:53 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/timer/TimerManager.kt
> +   * Starts the timer. The timer will run for a fixed duration of 6 hours.
Updated !

2024-11-28 15:57 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/timer/TimerManager.kt
> +        Log.d(TAG, "startTimerAction: fail to start timer: ${e.message}")
Changed, can you recheck ? :)

2024-11-28 16:01 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/timer/TimerManager.kt
> +  fun startActionForTesting(onSuccess: () -> Unit, onFailure: (Exception) -> Unit) {
Yeah really not ideal. I just couldn't find a way to mock failure, I'll retry...

2024-11-28 16:16 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/timer/TimerModel.kt
> +  suspend fun deleteTimerByTimerId(
I did the changes in Timer M and Timer M Supabase. However, I haven't yet implemented the VM delete functions

2024-11-28 16:18 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/timer/TimerModelSupabase.kt
> +      withContext(Dispatchers.IO) {
I did the changes, can you check ? :)

2024-11-28 16:24 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/timer/TimerViewModel.kt
> +class TimerViewModel(
Updated !

2024-11-28 17:23 UTC, francelu commented on app/src/test/java/com/android/periodpals/model/timer/TimerManagerTest.kt
> +class TimerManagerTest {
Did the changes in the tests !

2024-11-28 18:18 UTC, charliemangano approved these changes
Thanks for implementing the changes, LGTM

2024-11-28 18:21 UTC, merged