Feat/authentication/form-validation : Integrate form validation library into authentication screens
PeriodPals/periodpals pull request #263
Opened 2024-11-30 15:43 UTC by charliemangano

# Integrate form validation library into authentication screens
**This PR is still a WIP**

## Description
This PR introduces... It closes issue #...

## Changes

## Files 

#### Added
- file 1
- file 2
- ...
#### Modified

#### Removed

## Dependencies Added
- dependency 1 for XXX
- ...

## Testing

## Screenshots (if applicable)

2024-11-30 23:20 UTC, francelu requested changes
## Summary
This PR is a good clean up to validate fields. As the coaches mentioned, we're now using this Form Builder API. I found it really interesting to see how it worked. Good job doing these implementations !  

## Important
#### Code Quality
- Code is clean simple and consistent with rest of the code.
- I noticed you often do some code formatting clean-up using the `,`. Good, but I think not that meaningful. Of course it's nice visually and more consistent. However, I feel like it's a loss of time as we really want to focus on implementing more features ... xD

#### Functionality
- At first sight, the implementation looks good. While in reality, nothing works, not even login (on emulator).

#### Performance
- No significant performance concerns detected.
- Likely to improve performance.

#### Security
- No specific vulnerabilities noted.

## Testing
- Tests are updated to reflect the new validation logic and the use of `FormState`.  
- It’s great to see comprehensive tests for both the ViewModel and UI. Ensure edge cases like rapid user input or empty fields are covered.
- Some cases shouldn't happen. See screenshots.

## Documentation
- The PR description is thorough and provides a clear explanation of the `FormBuilder` library and how it has been integrated. Excellent job here!
- Missing a couple of updates on existing documentation (see comments).

## Suggestions
- Check comments for nitpick, documentation, suggestions / for later task.
- Check the screenshots bellow, nothing works :((
- Consider avoiding over-formatting unless it is strictly necessary. It’s nice for consistency but can be time-consuming without added functionality.  

## Steps before PR approved
- Check code comments.
- Check the screen shots below.
- Fix the authentication.
- Might need to change the tests or add some tests because they all pass while authentication doesn't work a bit in reality.

## Screenshots
| Password error message missing on `SignInScreen`  | ![image](https://github.com/user-attachments/assets/0db4b36d-3ef5-4b58-9c33-22a86717c2b6)  |
|--|--|
| One of my valid email addresses with wrong password doesn't display error messages correctly  | ![image](https://github.com/user-attachments/assets/77eb139e-fa6f-4863-820b-331d3749a999)  |
| Can't login whaaaat  | ![image](https://github.com/user-attachments/assets/1ae05c7c-ee18-46c8-8e7e-0d8568dac5c6)  |
| Error messages of don't match are not displayed  | ![image](https://github.com/user-attachments/assets/ec256f27-ae46-46fb-87e1-6fb981b99ae5)  |

2024-12-01 09:27 UTC, charliemangano commented
Hi @francelu, I'll respond to some things here!

> I noticed you often do some code formatting clean-up using the ,. Good, but I think not that meaningful. Of course it's nice visually and more consistent. However, I feel like it's a loss of time as we really want to focus on implementing more features ... xD

This is just a feature of my ktfmt settings, it adds it on its own when I run it!


> One of my valid email addresses with wrong password doesn't display error messages correctly

That's normal, as the checks for a valid email address became more strict: you need to have the format `<smth>@<smth>.<smth>`. Here, you're missing the `.<smth>`!


> Can't login whaaaat

You can't login because the email address is not valid. Even if you have an associated account in Supabase, this check catches the invalid email first and the login request never even goes to Supabase.


> Error messages of don't match are not displayed

This is normal as the email address is checked for first. If you try with a valid email address, the "Passwords do not match" error will show up.


> Password error message missing on SignInScreen

I understand this is the exact same behavior as before we integrated this new library, but it's still proper UX. I will try and make it consistent with how it was before, but since the tests still passed I thought it was not expected behavior.

2024-12-01 09:35 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/ui/authentication/SignIn.kt
>          )
This is out of the scope of my issue, but it's a very good idea. I created a task "Improve UX for input fields".

2024-12-01 09:39 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/ui/authentication/SignUp.kt
>  private const val DEFAULT_CONFIRMED_PASSWORD_VISIBLE = false
I'll make the naming consistent between both screens.
As for the use of a `private const val` for storing this value, I still think it's good practice. I'll explicit the type in the declaration and adjust the naming to something that makes you think more of a `Boolean`. I think since they're conceptually the same, I can also make it so that there is only a single `val` for this.

2024-12-01 09:39 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/ui/authentication/SignUp.kt
>  ) {
Will adjust! Nice catch

2024-12-01 09:48 UTC, charliemangano commented on app/src/test/java/com/android/periodpals/ui/authentication/SignInTest.kt
> +
Since the view model is mocked in the test, we need to return a value for when `authViewModel.formState` is called. This is what this line does.

The `formState` is declared and initialised in the `setUp`, with values equal to what is in the view model. It's not mocked since it's an external library, so it's passed as its own object, and that object acts on its own as it would in the code. The `formState` is already tested in the view model tests so I don't recheck it here.

I understand the confusion, but this simply stems from the fact that `formState` is not mocked, so you don't need lines like `when(formState.someMethod).thenReturn(someValue)`.

2024-12-01 09:49 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/authentication/SignUp.kt
>  private const val DEFAULT_CONFIRMED_PASSWORD_VISIBLE = false
Yes a single shared val would be good enough :)

2024-12-01 09:52 UTC, francelu commented
> This is just a feature of my ktfmt settings, it adds it on its own when I run it!

My bad, just keep doing it then ! :)

> That's normal, as the checks for a valid email address became more strict: you need to have the format <smth>@<smth>.<smth>. Here, you're missing the .<smth>!

My bad ://// I'll retry and approved if everything LGTM :))

2024-12-01 10:13 UTC, francelu approved these changes
## Summary
- The new changes are good, they work well and improve UX.  
- My bad for not having read thoroughly the documentation of Form Builder validation for emails.
- Everything LGTM ! :)

## Functionality
- Email is kept across the sign-in and sign-up screens. You might want to fix that, but it's a minor issue that doesn't block the user to login / sign-up.

## Documentation
- As mentioned earlier, two little updates :)

## Steps before PR merged
- Update the documentation as mentioned.
- Resolve comments.
- Then all good to go ! Good job !!

## Screenshots
| **Wrong email correct error messages**  | ![image](https://github.com/user-attachments/assets/fea24b69-52d3-44a4-8c4c-36ab36ced054)  |
|--|--|
| **Keeping track of email entered en SignIn screen**  | ![image](https://github.com/user-attachments/assets/9fca7008-c9a7-4bac-9e88-4c0f7ee097dc)  |
| **Right error messages in SignUp screen**  | ![image](https://github.com/user-attachments/assets/322248d2-7c20-4215-ad24-5194ab6d8e90)  |

2024-12-01 12:44 UTC, merged