Map improvements
PeriodPals/periodpals pull request #289
Opened 2024-12-07 16:56 UTC by lazarinibruno

# Map improvements

## Description
This PR introduces a few minor yet relevant changes to the app. It closes issue #203.

## Changes
- Map is able to change between dark mode and light mode
- If the app does not have internet connection, the map uses a local tile source
- Increased the size of the markers
- Added back the zoom in/out buttons

To implement the second point, I added a `NetworkChangeListener` class which, as the name suggests, listens to the state of the network. In the spirit of the service classes that we have implemented, it exposes the state of the network through a StateFlow `isNetworkAvailable`. Therefore, it suffices to listen to it in screens that need to react to the state of the network. 

## Files 

### Added

### Modified

### Removed

## Dependencies Added
None.

## Testing
For the moment, none.

2024-12-08 19:40 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/location/Location.kt
Good, it's more centred on campus now where our main typical user will be.

2024-12-08 19:40 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/map/Map.kt
>  private const val CUSTOM_THEME_NAME = "Custom theme"
This is unused. Remove it ?

2024-12-08 19:40 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/map/Map.kt
> +  mapView.setTileSource(TileSourceFactory.MAPNIK)
**Nitpick**: code understandability and cleanness ?
```suggestion
return if (isNetworkAvailable) mapView.setTileSource(customTileSource)
  else mapView.setTileSource(TileSourceFactory.MAPNIK)
```

2024-12-08 19:40 UTC, francelu commented on app/src/main/java/com/android/periodpals/services/NetworkChangeListener.kt
You might want to add some documentation if you don't want to be beaten by the coaches :')

2024-12-08 19:40 UTC, francelu commented on app/src/test/java/com/android/periodpals/services/NetworkChangeListenerTest.kt
LGTM. Tests pass !

2024-12-08 21:39 UTC, francelu requested changes
## Summary
Good implementation.  

However, when I tried on emulator, I was on map (worked well), turned on air-plane mode (still kinda worked), went on another screen, came back to map, had ugly grid.
![image](https://github.com/user-attachments/assets/d3a58f0b-9e30-47f1-b813-7c26a7824535)

## Important
#### Code Quality
- Generally consistent and readable.

#### Functionality
- Doesn't work as intended in offline mode.

## Testing
As I mentioned, this big bug slipped through the net.

## Documentation
- A few missing...

## Suggestions
- Check comments.
- Fix offline map bug.

## Steps before PR approved
- Check comments.
- Fix offline map bug.

2024-12-09 17:02 UTC, lazarinibruno commented on app/src/main/java/com/android/periodpals/ui/map/Map.kt
>  private const val CUSTOM_THEME_NAME = "Custom theme"
Good catch!

2024-12-09 17:02 UTC, lazarinibruno commented on app/src/main/java/com/android/periodpals/ui/map/Map.kt
> +  mapView.setTileSource(TileSourceFactory.MAPNIK)
Yes, I wanted to avoid using the `else` statement but, in retrospective, you're right that using an `else` makes it clearer.

2024-12-09 17:03 UTC, lazarinibruno commented on app/src/main/java/com/android/periodpals/services/NetworkChangeListener.kt
Hahaha, totally forgot about it. Thx.

2024-12-09 23:53 UTC, coaguila approved these changes
## Summary
As you said, `NetworkChangeListner` doesnt seem to be useful for this pr but is a welcomed addition because it does seem useful to have already even if there is no offline caching for maps. As you mentioned, this would create storage issues as well as osm not offering a solution, but if you are interested in storing locally, don't hesitate to look into the Room Jetpack Android Library.
## Important (which includes)
#### Code Quality
lgtm
#### Functionality
lgtm
## Testing
lgtm
## Documentation
Simple, quick, effecient
## Suggestions
Finish implementing France's requested changes.

2024-12-10 08:52 UTC, francelu approved these changes
## Summary
LGTM.

## Important
#### Functionality
- Works seamlessly as intended.

## Steps before PR approved
- Look at last comments and resolve as needed.

2024-12-10 08:52 UTC, francelu commented on app/src/main/java/com/android/periodpals/services/NetworkChangeListener.kt
Why do we still need `NetworkChangeListener` ? I don't think it's very meaningful to keep it in this PR even though we might need it for offline mode. TBD with @coaguila.

Same for the test class.

2024-12-10 08:52 UTC, francelu commented on app/src/main/res/drawable/alert_marker.xml
Might want to adapt it in Sprint 10 to the different screen sizes using the `Type.kt` if we have some time left.

2024-12-10 15:45 UTC, lazarinibruno commented on app/src/main/java/com/android/periodpals/services/NetworkChangeListener.kt
Had I known that the OSMDroid does not support "local" tile sources, I obviously wouldn't have implemented it. But given that I already did, lets keep it. Otherwise, doing a separate PR for `NetworkChangeListener` would mean someone else reviewing code that you and and @coaguila already did.

2024-12-10 15:49 UTC, lazarinibruno commented on app/src/main/res/drawable/alert_marker.xml
This is a good idea! However, it is not as straight-forward as it would seem. So lets leave it as a future task, as you suggest.

2024-12-10 15:50 UTC, merged