Feat/alert/alert lists location filter
PeriodPals/periodpals pull request #290
Opened 2024-12-07 21:32 UTC by agonzalez-r

# Alert Location Filtering: frontend modifications in `AlertsLists`

## Description
This PR closes issue #281 by introducing the new location filtering feature in `AlertsLists`, by adding the UI.

A Floating Action Button is displayed in the `PalsAlerts` screen, when clicked a Dialog appears, asking the user their location (possibility to choose “Current Location”) and a radius slider to select the radius of the filter, with respect to their position, as well as an “Apply FIlter” button and a “Reset Filter”, the latter displays all the alerts in the database again. See the screenshot for a better look! 
Disclaimer: I’m not sure if it is actually relevant to have a button to reset the filter, but for the current use of the app, it is very helpful to be able to remove the filter. 

## Changes
- Added a function `resetAlertsWithinRadius()` to the `AlertViewModel`, I actually feel that the name of this function is not very clear, if you have suggestions please comment them. 
- Also changed the mutable state palsAlerts in `AlertViewModel` to take the value of `alertsWithinRadius` (and filter them to remove the user’s own alerts).
- Added composables for the **Filter FAB UI and the Dialog**, in `AlertComponents` because this button will be shared with the `Map` screen. 
- Adapted `AlertsLists` screen to call these new components and display the correct lists of alerts depending on the filter.

## Files 

#### Added
None. 

#### Modified
- `app/src/main/java/com/android/periodpals/MainActivity.kt`: refactoring, we need to pass some others VM to this class now
- `app/src/main/java/com/android/periodpals/model/alert/AlertViewModel.kt`: added one function and changed the value of `palsAlerts` 
- `app/src/main/java/com/android/periodpals/resources/C.kt`: new components = new test tags 
- `app/src/main/java/com/android/periodpals/ui/alert/AlertLists.kt`: main changes, the display of the Filter button and added functionality
- `app/src/main/java/com/android/periodpals/ui/components/AlertComponents.kt`: new components 

#### Removed
None. 

## Dependencies Added
None.

## Testing
Tested the functionality of the filter FAB in `AlertsListsScreen`, meaning the correct display of components and the actions of the buttons. 
I also added a test for `resetAlertsWithinRadius()` in the VM tests, but this is a very simple function, so the test is very simple as well. 
Any ideas to improve these tests are welcome, as always. 

## Screenshots (if applicable)
<img width="422" alt="Screenshot 2024-12-07 at 22 20 27" src="https://github.com/user-attachments/assets/56c5e94b-be73-4233-a4cb-990a561f119e">

2024-12-08 10:04 UTC, agonzalez-r commented
A little note: the SonarCloud report says there is
> [76.5% Coverage on New Code](https://sonarcloud.io/component_measures?id=PeriodPals_periodpals&pullRequest=290&metric=new_coverage&view=list)

But Line Coverage is at 90.4%, which is what is most important

2024-12-08 13:49 UTC, lazarinibruno approved these changes
## Summary

Thanks for your contribution. It is particualrly helpful since I'm implementing the map 😼.

## Code quality

- Clean and concise changes in the alert view model.
  
- Proper addition of test tags.
  
- Documentation added where needed.
  

## Testing

- You tested both that the `FilterFab` and `Dialog` are displayed when in `Pals Alerts`
  
- and that the filter works by mocking it 🔥.
  
## Suggestions

As discussed in the group chat, it would be cool to have a visual indicator that there is a filter active. I managed to get something half-descent with:

```kotlin
if (palsTab) {
    Box(
      contentAlignment = Alignment.TopEnd,
      modifier = Modifier.size(72.dp)
    ) {
      FloatingActionButton(
        onClick = { onClick() },
        containerColor = MaterialTheme.colorScheme.tertiaryContainer,
        contentColor = MaterialTheme.colorScheme.onTertiaryContainer,
        modifier = Modifier.testTag(AlertListsScreen.FILTER_FAB)
      ) {
        Icon(imageVector = Icons.Default.FilterAlt, contentDescription = "Filter Alerts")
      }

      Box(
        modifier = Modifier
          .size(16.dp)
          .background(Color.Red, shape = CircleShape), // Circular bubble
      )
```
That looks like this:

![image](https://github.com/user-attachments/assets/246050f0-0518-47c7-b413-4d16ef7f0010)

## Steps before merge

Please consider my comments. Otherwise, code LGTM.

2024-12-08 13:49 UTC, lazarinibruno commented on app/src/main/java/com/android/periodpals/ui/components/AlertComponents.kt
> +        Text(
**Suggestions**:
Consider doing the conversion to km as follows: 

```kotlin
if (sliderPosition < 1000) "Radius: $sliderPosition m from your position"
else "Radius: ${sliderPosition / 1000} km from your position",
```

Also, extract all of the constant values to `private const val` for maintainability.

2024-12-08 13:49 UTC, lazarinibruno commented on app/src/main/java/com/android/periodpals/ui/alert/AlertLists.kt
> +            radius = 100.0
**Suggestion**: extract the radius to a `private const val`.

2024-12-08 13:50 UTC, francelu requested changes
## Summary
This pull request introduces a new location filtering feature to the AlertLists screen. The feature includes a Floating Action Button (FAB) that triggers a dialogue for users to set a location and radius filter for alerts.

## Important

#### Code Quality
- Code readability and consistency are well-maintained.
- The addition of new parameters to existing functions is clear and follows Kotlin conventions.
- State management using `mutableStateOf` is appropriate.

#### Functionality
- The location filtering feature is correctly implemented.
- The changes to `AlertViewModel` ensure proper handling of filtered alerts.
- Edge cases such as resetting the filter are handled.
- The integration of the filter dialogue and FAB (Floating Action Button) in `AlertListsScreen` is seamless.

#### Performance
- The use of `mutableStateOf` ensures efficient state management.

#### Security
- No security concerns identified with the changes.

## Testing
- The tests validate the correct display and interaction of the filter components.

## Documentation
- Code comments and documentation are provided for new functions and parameters.
- The purpose and usage of the new filter feature are well-documented.

## Suggestions
- Check code comments.
- Reset filter when the user first creates an account. If you do it on the screen, it will be reset every time the user comes to pals alert list screen.
- **To be discussed**: maybe use the user/profile's radius for this filtering thing.
- Visually noticeable if one (or more filters in the near future) is activated or not.

## Steps before PR approved
- Check comments and the above suggestions.
- Verify that the filter functionality works as expected on different screen sizes and device orientations.

2024-12-08 13:55 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/ui/alert/AlertLists.kt
>    val myAlertsList = alertViewModel.myAlerts.value
I did think about changing it for consistency with the `palsAlertsList` but there is actually no need to do so, the only cases where that list needs updating is when the user creates an alert or when it updates it, since both of these cases require navigating back to the screen, the list is automatically updated. But that is not the case for `palsAlerts` because the filter dialog is not a screen that navigates back to `AlertsLists`, it stays in it, so that's why I need a mutable list in that case.

2024-12-08 14:05 UTC, agonzalez-r commented
@francelu 

> Reset filter when the user first creates an account. If you do it on the screen, it will be reset every time the user comes to pals alert list screen.

For the moment I'll reset the filter each time the user re-opens the `AlertsLists` screen. After we discuss and define the parameter radius that will be stored for each user, I will use that value as default radius and I will modify the reset in that same PR, but I prefer not doing those changes in the PR, and taking the time to think and discuss what's better for the UX. Let's keep this PR only about the filter and its functionality.

2024-12-08 16:27 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/ui/components/AlertComponents.kt
> +fun FilterFab(palsTab: Boolean, onClick: () -> Unit) {
I'll remove the variable altogether as @francelu suggested!

2024-12-08 17:40 UTC, agonzalez-r commented
New added features:
- All alerts are displayed upon opening the `AlertsLists` screen. In the future, we will probably save the value of the preferred radius in the user data class. 
- FAB bubble indicating that the filter is on or not. Thanks @lazarinibruno for the hint ;)

<img width="355" alt="Screenshot 2024-12-08 at 18 36 56" src="https://github.com/user-attachments/assets/46bdbf3e-7bde-4a2a-baae-3e03c5ec193a">

2024-12-08 18:08 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/model/alert/AlertViewModel.kt
I renamed the function to `removeLocationFilter()` as it describes better what it does, but thank you for the input :)

2024-12-08 19:10 UTC, francelu approved these changes
## Summary
LGTM. Good implementation of the changes and the new bubble to differentiate if there are filters or not.

## Suggestions
- See comments.

## Steps before PR merged
- Check and resolve comments (documentation update and little nitpick).
- Good job overall !

2024-12-09 07:58 UTC, agonzalez-r commented on app/src/main/java/com/android/periodpals/ui/alert/AlertLists.kt
1000m is really far, I don't agree that that would be a better value because in reality, I really consider it to be the maximum actually. 
But for the moment there is no really a "default" radius, since with the modifications I made, all the alerts are first displayed, if the user wants to filter they need to input a radius themselves.

2024-12-09 12:20 UTC, merged