Feat/timer/update instructions
PeriodPals/periodpals pull request #296
Opened 2024-12-10 10:42 UTC by francelu

# Update instructions to Supabase automatically

## Description
This PR several significant changes to the `Timer` feature in the `periodpals` Android application. It closes issue #287.  

This should help @charliemangano with timer reminders implementation.

## Changes
The changes include enhancements to the `Timer` data model, updates to the `TimerViewModel`, and additions to the `TimerRepository` interface and its implementation. These changes aim to improve the functionality and robustness of the timer feature.

## Files 

### Added
- None.

### Modified
#### Enhancements to Timer Data Model:
* `app/src/main/java/com/android/periodpals/model/timer/Timer.kt`: Added `id` and `instructionText` properties to the `Timer` data class, with `id` being a unique identifier generated upon creation.
* `app/src/main/java/com/android/periodpals/model/timer/TimerDto.kt`: Updated `TimerDto` to include `id` and `instructionText` properties, and modified the conversion methods to handle these new properties.

#### Updates to TimerViewModel:
* `app/src/main/java/com/android/periodpals/model/timer/TimerViewModel.kt`: Introduced new constants, mutable states for active timer and running status, and methods for loading, starting, stopping, resetting, and updating timers. Added logic to handle reminders based on the remaining time.

#### Additions to TimerRepository Interface:
* `app/src/main/java/com/android/periodpals/model/timer/TimerModel.kt`: Added `getActiveTimer` and `updateTimer` methods to the `TimerRepository` interface, along with their respective documentation.

#### Implementation of New Methods in TimerRepository:
* `app/src/main/java/com/android/periodpals/model/timer/TimerModelSupabase.kt`: Implemented `getActiveTimer` and `updateTimer` methods in `TimerRepositorySupabase` class. These methods interact with the Supabase backend to retrieve and update timer data.

#### Miscellaneous Changes:
* `app/src/main/java/com/android/periodpals/MainActivity.kt`: Refactored `MainActivity` to use a `lateinit` property for `TimerViewModel`.
* `app/src/main/java/com/android/periodpals/ui/timer/TimerScreen.kt`: Removed an unused import statement.

### Removed
- None.

## Dependencies Added
- None.

## Testing

2024-12-10 17:57 UTC, charliemangano requested changes
## Summary
Nice addition to the timer, this looks like it was much more complicated than we thought! 
## Important
#### Code Quality
Code is still readable even with these additions, and the model and view model are consistent with our architecture.
#### Functionality
The timer still works as expected, and now sends updates to the `public.timers` table even in the background, good job! 
## Testing
Tests are updated and complete, good job!
## Documentation
Docs is up-to-date, nicely done!
## Suggestions
Take a look at the comments. Most are nitpicks but do address the passing of callbacks to `computeAverageTime` remark.
## Steps before PR approved
Fix the `computeAverageTime` callbacks, otherwise all good!

2024-12-10 18:05 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/timer/TimerModelSupabase.kt
> +const val ACTIVE_TIMER_TIME = -1L
Could use null, would require a couple of changes. Doing them right now !

2024-12-10 18:34 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/timer/TimerModelSupabase.kt
> +      withContext(Dispatchers.Main) { supabase.postgrest[TIMERS].insert(timerDto) }
It wasn't there in User Model either, I was trying to make timer automatically update. I had troubles with Supabase and RLS. So I tried everything, including deleting this, which doesn't seem to bother.

2024-12-10 18:36 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/timer/TimerViewModel.kt
> +private const val POSITIVE_REMINDER_TEXT = "You've got this! Almost time to change your tampon!"
Then I would also have to change the screen's title to... `Protection Timer ` ??

2024-12-10 18:37 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/timer/TimerViewModel.kt
> + * @property remainingTime Public live data of the remaining time.
We did that for alert VM, I'm unsure either...

2024-12-10 18:37 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/timer/TimerViewModel.kt
> +private const val NEGATIVE_REMINDER_TEXT =
well it's just when the 6 hours haven't been reached yet or already has been.

2024-12-10 18:42 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/timer/TimerViewModel.kt
> +            computeAverageTime(uid, onSuccess, onFailure)
Okay

2024-12-10 18:43 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/timer/TimerViewModel.kt
> +            val nonNegativeTimes = timerList.map { it.time }.filter { it >= 0L }
Logic has been changes since the `Timer`'s `time` is a `Long?` now.

2024-12-10 18:46 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/timer/TimerScreen.kt
> +      onSuccess = { timerViewModel.loadActiveTimer(uid = authUserData.value?.uid ?: "") })
Added, even though there is already a Log in the `loadAuthenticationUserData()`'s `onSuccess = { ... }`.

2024-12-10 22:39 UTC, taghizadlaura approved these changes
## Summary
LGTM :
This PR introduces significant updates to the `Timer` feature in the `periodpals` Android app. The main focus is enhancing the `Timer` data model, updating the `TimerViewModel`, and refining the `TimerRepository` interface and its Supabase implementation to enable automatic Supabase updates while the app is open in the background. 

## Important

### Code Quality
LGTM :
The code is well-structured, with consistent naming conventions and clear documentation. 

### Functionality
LGTM :
The updated implementation now seems to support automatic updates to Supabase when the app is running in the background. The new properties in the data model and the additional repository methods seems to ensure that timer state management is accurate and that timer reminders are properly handled.

### Performance
No performance issues.

### Security
No security issues.

## Testing
LGTM :
The testing is well updated, and the new tests are thorough, providing great coverage of the updated functionality.

## Documentation
LGTM : 
The PR provides sufficient documentation in code comments and the PR description itself. The documentation highlights the current limitations, such as the app not supporting timer updates when closed.

## Suggestions
I wanted to mention that the remaining issues with the timer are as follows: it is the same across all accounts, and I'm not sure if this is planned to be addressed in another PR. Additionally, there is still an issue with the displayed text and the hourglass not being in the correct state when switching screens.

## Steps before PR approved
LGTM, but I may not be the most informed reviewer for this PR, so please address Charlie's comment before merging. Also, feel free to check my suggestions and add anything you think is relevant.

2024-12-10 22:39 UTC, taghizadlaura commented on app/src/test/java/com/android/periodpals/model/timer/TimerModelSupabaseTest.kt
LGTM! Great testing!

2024-12-10 22:39 UTC, taghizadlaura commented on app/src/test/java/com/android/periodpals/model/timer/TimerViewModelTest.kt
Same great testing!

2024-12-10 22:39 UTC, taghizadlaura commented on app/src/test/java/com/android/periodpals/ui/timer/TimerScreenTest.kt
LGTM! Good update to the existing tests!

2024-12-11 08:10 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/model/timer/TimerViewModel.kt
> + * @property remainingTime Public live data of the remaining time.
We can leave it as is and come back to it when we clean up the docs

2024-12-11 08:28 UTC, francelu commented
> ## [![Quality Gate Passed](https://camo.githubusercontent.com/f7c890f34e0efe8252e17e9afd5a85aa22fc9c81b42a0ec3d4821af9f55f250d/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f71672d7061737365642d323070782e706e67)](https://sonarcloud.io/dashboard?id=PeriodPals_periodpals&pullRequest=296) **Quality Gate passed**
> 
> Issues ![](https://camo.githubusercontent.com/187ba88c264795e888bdd18141ef29390601e5110d4e9c8cc48f2f8afc183ba0/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f7061737365642d313670782e706e67) [5 New issues](https://sonarcloud.io/project/issues?id=PeriodPals_periodpals&pullRequest=296&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true) ![](https://camo.githubusercontent.com/86e5c40907bf9e8933fe6bcf185f7076622a76a3bef4b6d2b5fd583959409aef/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f61636365707465642d313670782e706e67) [0 Accepted issues](https://sonarcloud.io/project/issues?id=PeriodPals_periodpals&pullRequest=296&issueStatuses=ACCEPTED)
> 
> Measures ![](https://camo.githubusercontent.com/187ba88c264795e888bdd18141ef29390601e5110d4e9c8cc48f2f8afc183ba0/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f7061737365642d313670782e706e67) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=PeriodPals_periodpals&pullRequest=296&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true) ![](https://camo.githubusercontent.com/187ba88c264795e888bdd18141ef29390601e5110d4e9c8cc48f2f8afc183ba0/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f7061737365642d313670782e706e67) [72.3% Coverage on New Code](https://sonarcloud.io/component_measures?id=PeriodPals_periodpals&pullRequest=296&metric=new_coverage&view=list) ![](https://camo.githubusercontent.com/187ba88c264795e888bdd18141ef29390601e5110d4e9c8cc48f2f8afc183ba0/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f7061737365642d313670782e706e67) [0.0% Duplication on New Code](https://sonarcloud.io/component_measures?id=PeriodPals_periodpals&pullRequest=296&metric=new_duplicated_lines_density&view=list)
> 
> [See analysis details on SonarQube Cloud](https://sonarcloud.io/dashboard?id=PeriodPals_periodpals&pullRequest=296)

@taghizadlaura  
About the timer's text not updating, it was because the `time` column on Supabase is now a `Long?` and I hadn't cleaned the table to make it work properly. Now that it has been done, I think it works seamlessly.

2024-12-11 08:28 UTC, francelu commented
> ## Suggestions
> 
> I wanted to mention that the remaining issues with the timer are as follows: it is the same across all accounts, and I'm not sure if this is planned to be addressed in another PR. Additionally, there is still an issue with the displayed text and the hourglass not being in the correct state when switching screens.

@taghizadlaura  
About the timer's text not updating, it was because the time column on Supabase is now a Long? and I hadn't cleaned the table to make it work properly. Now that it has been done, I think it works seamlessly.

2024-12-11 09:38 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/model/timer/TimerViewModel.kt
> +private const val POSITIVE_REMINDER_TEXT = "You've got this! Almost time to change your tampon!"
No need for that since the codebase is not directly visible to the user! However, please change the text for the notification since it **is** actually visible, and our users might not want that.

2024-12-11 09:46 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/model/timer/TimerViewModel.kt
> +private const val POSITIVE_REMINDER_TEXT = "You've got this! Almost time to change your tampon!"
I don't think it's necessary since it's internal to the app so the user can choose whether to show it to people or not, whereas the notifs just pop-up: if the user is showing something else on their phone to someone, or even has left it face up on their desk, it would still show up and the user can't do anything about it.

Additionally, (and sorry to not have caught that initially) we should have the remaining time somewhere in the notification, so I believe we should consider changing the messages like this:
- "It's been more than X hours! You've got this! Almost time to change your protection!"
- "It's been 6 hours! Change your tampon for you comfort and health!"

I know this text is also used on the UI but I think it still makes sense.

2024-12-11 09:49 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/timer/TimerViewModel.kt
> +private const val POSITIVE_REMINDER_TEXT = "You've got this! Almost time to change your tampon!"
Good idea ! Good UX.

I'll make this change asap.

2024-12-12 13:26 UTC, charliemangano approved these changes
LGTM! Thanks for the changes :) Take care to run ktfmt before merging

2024-12-12 13:26 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/model/timer/TimerModelSupabase.kt
> +                  limit(1)
Good thinking!

2024-12-12 13:26 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/model/timer/TimerViewModel.kt
> +            val roundedTime = hours + if (halfHours >= 1) 0.5 else 0.0
nitpick: I think these numbers could be extracted so the code is more understandable

2024-12-12 13:26 UTC, charliemangano commented on app/src/main/java/com/android/periodpals/model/timer/TimerViewModel.kt
> +                "It's been more than $roundedTime hours! You've got this! Almost time to change your protection!"
Good thinking!

2024-12-12 13:31 UTC, francelu commented on app/src/main/java/com/android/periodpals/model/timer/TimerViewModel.kt
> +            val roundedTime = hours + if (halfHours >= 1) 0.5 else 0.0
Mmh okaay of course ! Doing it :)

2024-12-12 14:31 UTC, merged