Feat/profile/UI
PeriodPals/periodpals pull request #37
Opened 2024-10-15 12:08 UTC by taghizadlaura

This branch implements the initial design of the ProfileScreen. The focus is on creating the UI layout for displaying essential user profile elements, including the user's avatar, name, description, and review sections.

#### Features Implemented:

* Basic UI layout for the profile name, description, and reviews.
* Placeholder elements for user data, as the ViewModel and Model are not yet implemented.

<img src="https://github.com/user-attachments/assets/b8ec104a-2228-4aa2-aa83-06b123ed0d12" alt="image" width="400"/>

2024-10-15 16:33 UTC, Harrish92 requested changes
**Summary:**

Great job on the `CreateProfile` composable! The structure is clear and the use of state management is well-implemented. However, some improvements could be made.

**Recommendations:**

1. For coherence, consider changing the `Image` composable in `ProfileAvatar` to `GlideImage`, similar to how it is used in `CreateProfile`.
2. The "Description" text in `ProfileDetails` seems redundant. Please remove it to avoid repetition and improve clarity.

Keep up the good work!

2024-10-15 18:35 UTC, taghizadlaura commented
The preview doesn't work with the GlideImage but we can run it and see this now : 

<img src="https://github.com/user-attachments/assets/e5895b6e-62ce-4c2b-8fb3-63fdb5ff6642" alt="image" width="400"/>

2024-10-15 18:56 UTC, Harrish92 approved these changes
LGTM

2024-10-15 19:48 UTC, francelu commented on app/src/main/java/com/android/periodpals/ui/profile/ProfileScreen.kt
> +      text = "Displayed Name",
As designed in the Figma, use "Name" instead of "Displayed Name", change your tests accordingly if needed.

2024-10-15 19:49 UTC, francelu commented on app/src/androidTest/java/com/android/periodpals/ui/profile/ProfileScreenTest.kt
> +    composeTestRule.onNodeWithTag("profileName").assertExists("Displayed Name")
Use `assertTextEquals()` instead of `assertExists()`.

2024-10-16 08:40 UTC, taghizadlaura commented
Now I changed the tests with assertTextEquals() and  the Display Name into Name as France recommanded : 

<img src="https://github.com/user-attachments/assets/4744bdc0-ed01-4dd9-8e87-476476a11cfa" alt="image" width="400"/>

2024-10-16 08:50 UTC, francelu approved these changes
LGTM :)

2024-10-16 08:51 UTC, merged