Feat/profile/view model
PeriodPals/periodpals pull request #50
Opened 2024-10-18 00:03 UTC by Harrish92

### Pull Request

**Title:** integrate Supabase for user profile

**Description:**
This PR introduces the integration of Supabase into the project.

**Changes:**
1. **Gradle Configuration:**
   - Updated `build.gradle.kts` to read `supabaseUrl` and `supabaseKey` from `local.properties` and pass them to the Kotlin code.

2. **User Repository:**
   - Updated `UserRepositorySupabase` to use the Supabase client for loading and creating user profiles.

3. **Tests:**
   - Added unit tests for `UserRepositorySupabase` using JUnit and Mockito.

**Files:**
#### Added
- `src/main/java/com/android/periodpals/model/SupabaseClient.kt`
- `src/test/java/com/android/periodpals/model/user/UserRepositorySupabaseTest.kt`

#### Modified
- `build.gradle.kts`
- `src/main/java/com/android/periodpals/model/user/UserRepositorySupabase.kt`

**Dependencies Added:**
- `io.github.jan.supabase:supabase-kt` for Supabase integration

**Testing:**
- Verified that the Supabase client initializes correctly with the provided URL and key.
- Ensured that user profiles can be loaded and created successfully.
- Ran unit tests to confirm the functionality of `UserRepositorySupabase` and `UserViewModel`.

2024-10-18 00:53 UTC, francelu requested changes
## Summary
PR is unreviewable due to 21 modified files, most unrelated to the PR, and lack of documentation.

## Important
### Code Quality
- **Readability**: Code lacks documentation, making it unclear.
- **Consistency**: Likely using wrong Gradle ktfmt, causing unnecessary file changes.

### Functionality
- Unclear due to lack of explanation and documentation.

## Testing
- Mocking something that isn't used afterward.

## Documentation
- None provided. I can't guess what the code or functions do.

## Suggestions
- Ensure ktfmt passes before PR.
- Limit changes to relevant files.
- Add documentation to explain functionality.

## Steps before PR approval
- Reduce scope to relevant changes.
- Fix formatting.
- Add documentation.
- Put PR in draft.

2024-10-18 00:59 UTC, coaguila submitted a review, later dismissed
Lack of documentation makes this review hard to judge at all. The CI modifications should be dedicated to their own branch perhaps. Formatting seems to be off from the rest of the project.

2024-11-03 17:02 UTC, francelu requested changes
## Summary
Please address the changes and points I mentioned in the code and file comments to enhance the quality and maintain consistency.

## Important
#### Code Quality
- Ensure consistency and readability improvements based on comments.

#### Functionality
- Confirm changes align with the intended functionality and fix noted issues.

## Testing
- Ensure updated tests align with the changes and maintain thorough coverage.

## Documentation
- Update any relevant documentation to reflect modifications.

## Suggestions
- **Review and apply the suggested changes in the code comments for improved clarity and consistency.**

## Steps before PR approved
1. Implement the adjustments highlighted in the code comments.
2. Verify that the modifications are tested and documented as needed.

2024-11-03 19:23 UTC, coaguila commented on app/src/test/java/com/android/periodpals/model/user/UserViewModelTest.kt
> +     */
was the previous implementation of  `loadUserProfile` that did not use callbacks

2024-11-03 19:23 UTC, coaguila commented on app/src/test/java/com/android/periodpals/model/user/UserViewModelTest.kt
> +     */
will delete

2024-11-03 21:48 UTC, francelu approved these changes
LGTM.  
Please fix the two small typos mentioned in the code comment for consistent test naming before merging the PR.

2024-11-03 21:48 UTC, francelu commented on app/src/test/java/com/android/periodpals/model/user/UserRepositorySupabaseTest.kt
> +  fun `createUserProfile successful`() {
Can't you call the tests
```markdown
loadUserProfileIsSuccessful
// and
createUserProfileIsSuccessful
```
instead of
```markdown
fun `loadUserProfile successful`()
// and
fun `createUserProfile successful`()
```
?  
As I understand, your test names have spaces in them, where we don't have any in all our other tests. Could you modify that to stick to other tests' naming convention ?

2024-11-04 12:35 UTC, coaguila commented on app/src/test/java/com/android/periodpals/model/user/UserRepositorySupabaseTest.kt
> +  fun `createUserProfile successful`() {
I originally was copying @charliemangano tests on authentication model and we kept it so in our works but i don't mind changing but perhaps we should revisit test naming conventions in an another pr? idk

2024-11-04 17:11 UTC, charliemangano requested changes
Thanks a lot for the work! 

I realised I forgot something while reading over, so I added a new comment (sorry).  

I also unresolved other comments that you marked as resolved but didn't actually resolve. Either apply the changes or explain why you're not in response to the comments so I can understand the decisions made.  

As mentionned in the original review, can you also rename `UserRepository.kt` to `UserModel.kt` and so on in other files for consistency with the rest of the project.

2024-11-04 17:11 UTC, charliemangano commented on app/src/test/java/com/android/periodpals/model/user/UserRepositorySupabaseTest.kt
> +                      ",\"dob\":\"test\"}" +
I thought I had mentioned it but going back I think my comment did not save.
Could you have different values for each element? That would make the tests more robust.  

Also, extract the values in variables since you reuse them a lot.

2024-11-05 17:52 UTC, coaguila commented on app/src/test/java/com/android/periodpals/model/user/UserViewModelTest.kt
> +        .createUserProfile(any<User>(), any<() -> Unit>(), any<(Exception) -> Unit>())
i have updated the code so that it does :)

2024-11-07 21:38 UTC, Harrish92 commented on app/src/test/java/com/android/periodpals/model/user/UserRepositorySupabaseTest.kt
> +  fun `createUserProfile successful`() {
I decided to rename the tests.

2024-11-08 07:25 UTC, charliemangano approved these changes
LGTM! Thank you for the changes!

2024-11-08 07:34 UTC, merged