fix/authentication/signin-ui-tests : Fix and complete UI tests for SignInScreen
PeriodPals/periodpals pull request #73
Opened 2024-10-28 09:17 UTC by charliemangano

# Fix and complete UI tests for AlertScreen
**This PR is still a WIP**
## Description
This PR introduces...  It closes issue #71 and fixes part of #63 .
## Changes
Added dependencies to make mockito work in androidTests, and properly mocked `NavigationActions`. 
## Files 
#### Added
None
#### Modified
- `app/build.gradle.kts` and `gradle/libs.versions.toml`: add the missing dependency

#### Removed
None
## Dependencies Added
- [`com.linkedin.dexmaker:dexmaker-mockito-inline`](https://stackoverflow.com/a/67337292) to make mockito work with androidTests. Had to remove `libs.mockito.android` for androidTests as a consequence
## Testing

2024-10-29 19:51 UTC, coaguila approved these changes
There's a couple of comments but are all nitpicks but overall LGTM.

2024-10-29 19:51 UTC, coaguila commented on app/src/androidTest/java/com/android/periodpals/ui/authentication/SignInTest.kt
> +  private lateinit var authViewModel: AuthViewModel
Perhaps a nitpick, you can add a `@Mock` tag to automatically innit mock classes without having to do it on `setUp()`. This may make the code cleaner.

2024-10-29 19:51 UTC, coaguila commented on app/src/androidTest/java/com/android/periodpals/ui/authentication/SignInTest.kt
> +    composeTestRule.onNodeWithTag("signInNotRegistered").performClick()
Perhaps a nitpick but maybe add a space above to make it like the other tests.

2024-10-31 10:45 UTC, taghizadlaura requested changes
## Summary
Please see comments.

## Important

#### Code Quality
- LGTM

#### Functionality
- See comments

## Testing
- See comments

## Documentation
- LGTM

## Suggestions
- Maybe add more tests to cover edge cases, such as network errors during login.

## Steps before PR approved
- See comments

2024-10-31 10:59 UTC, charliemangano commented
> Maybe add more tests to cover edge cases, such as network errors during login.

This should be handled at the VM level, so those tests would be out of the scope of this PR.

2024-10-31 11:15 UTC, taghizadlaura approved these changes
LGTM now

2024-10-31 11:16 UTC, merged