fix: fix UI tests for M1: SignUp
PeriodPals/periodpals pull request #96
Opened 2024-10-30 13:32 UTC by taghizadlaura

# Fix UI tests for M1: SignUp

## Description
This PR introduces UI tests for the SignUpScreen component in the authentication module. It validates various user input scenarios to ensure proper error handling and navigation flow. It closes issue #76.

## Changes
I added more tests, including tests for the calls to the ViewModel. Now the navigation tests also work.

## Files 

#### Modified
- `SignUpScreenTest.kt`

2024-10-30 18:16 UTC, charliemangano requested changes
## Summary
These tests are very complete, good job! Small changes here and there, check the comments!
## Important
#### Code Quality
Very well formatted code, very consistent as well. I like that you extracted email and password variations in a companion object, it helps with consistency and error checking.
#### Functionality
I think the tests check for the proper things, and correctly. Be careful of edge cases though, see comments.
## Testing
The tests pass and are very  complete! Great job:)
## Documentation
Code is self-documenting thanks to the function and variable clear nomenclature!
## Suggestions
See comments
## Steps before PR approved
See comments. Any comment that is not annotated with "nitpick" has to be resolved before I approve this PR.

2024-10-31 12:51 UTC, francelu commented on app/src/androidTest/java/com/android/periodpals/ui/authentication/SignUpTest.kt
> +    // TODO: Supabase integration for account creation
I had put this at the very begging when implementing the UI. That was were I though the account validation with Supabase would be done, but it didn't in the end. So, I think delete that line 289.

2024-10-31 12:53 UTC, taghizadlaura commented on app/src/androidTest/java/com/android/periodpals/ui/authentication/SignUpTest.kt
> +        .thenReturn(mutableStateOf(UserAuthState.Success("User is logged up")))
wouldn't it be "signed up" ?

2024-10-31 13:38 UTC, charliemangano commented on app/src/androidTest/java/com/android/periodpals/ui/authentication/SignUpTest.kt
> +        .thenReturn(mutableStateOf(UserAuthState.Success("User is logged up")))
ah yes, you're right

2024-10-31 14:14 UTC, francelu approved these changes
## Summary
LGTM. 

## Important
#### Code Quality
- The separation of tests for "doesNotCallVM" seems redundant but maintains consistency with `SignInScreen`.

#### Functionality
- The tests correctly validate expected behaviors.

## Steps before PR approved
- None, keep up the good work!

2024-10-31 15:04 UTC, charliemangano approved these changes
Thanks for applying the changes! All tests pass and seem correct:)
LGTM

2024-10-31 15:05 UTC, merged